In [1]:
import pandas as pd
import numpy as np
import sklearn.model_selection as model_selection
from sklearn.covariance import EllipticEnvelope
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest
avg=0

## Ethereuem Address 1 
### 0x0067f95a79c3c404a9d128168ddfdf3cb70c0852

In [2]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\1_0x0067f95a79c3c404a9d128168ddfdf3cb70c0852.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x3c2381ba56d7ac52afe332ef765bc54dea6e39adc376...,4520344,1510237329,11/9/2017 2:22:09 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,6.553600e-14,0.000221,0.047815,319.66
1,0xa7b6a71a061f25585d2089ed0b6e6e6d92315f5b0205...,4520499,1510239325,11/9/2017 2:55:25 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xe7844a3cbc712652fb97f6170603fd7d4b1cd6f1,1.786700e-02,0.000252,0.054646,319.66
2,0x0e922e72e2015f9d964c03e38b724ce89af21fb02c0b...,4551503,1510668562,11/14/2017 2:09:22 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x8287ae7b97de14609db95ceb655de3cee54792d5,8.488310e-01,0.000420,0.091077,334.72
3,0xf4e38b199516b53775197097292dc6fdbbd6bd280abb...,4556239,1510734355,11/15/2017 8:25:55 AM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x0f9d959667be0fd0bd2917feba0aab7ac4ca9ce7,8.307040e+00,0.000315,0.068308,331.20
4,0xa3062f463750a33d9abc2a889e2fa6006341459eaef0...,4556641,1510740298,11/15/2017 10:04:58 AM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x8287ae7b97de14609db95ceb655de3cee54792d5,8.310500e-01,0.000420,0.091077,331.20
...,...,...,...,...,...,...,...,...,...,...
3079,0x4d60eb19fb7ae5b36d3e2424ba7a2a6ce7b59257600e...,8574536,1568824911,9/18/2019 4:41:51 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xcdd84fda733bf6e69e4ba29076dcdcb75afcd3a0,2.447829e-01,0.000441,0.095631,210.50
3080,0x33ffe7eb6b23d79da4c09c4cae78d97a4b0c0bed8da4...,8574545,1568825019,9/18/2019 4:43:39 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x0351061624f76fb70090054b908235f0b79c2005,1.225749e+00,0.000420,0.091077,210.50
3081,0x66301c137fd34bb11697e78c6ba50cc49c5ef5979618...,8574599,1568825663,9/18/2019 4:54:23 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xf98f559be1440f6867bf9cd70c728af74957c524,1.019297e+01,0.000420,0.091077,210.50
3082,0x355c02d1b97b3c87c9235279e11f751146a30a11d0c8...,8575523,1568837807,9/18/2019 8:16:47 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x4eaaa5eb8eaf08a6fdfbdd263354ae8814b1c966,1.003796e+00,0.000420,0.091077,210.50
3083,0x7fbf4160c9c2ae7431334e2cf1ca47a75934388b76b9...,8579448,1568891073,9/19/2019 11:04:33 AM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x8fbaad60c55f623158c42d83fb125bd1f3444461,1.007951e+00,0.000630,0.136616,221.29

### Pre-Processing

In [3]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0       6.553600e-14     0.000221     0.047815                 319.66
1       1.786700e-02     0.000252     0.054646                 319.66
2       8.488310e-01     0.000420     0.091077                 334.72
3       8.307040e+00     0.000315     0.068308                 331.20
4       8.310500e-01     0.000420     0.091077                 331.20
...              ...          ...          ...                    ...
3079    2.447829e-01     0.000441     0.095631                 210.50
3080    1.225749e+00     0.000420     0.091077                 210.50
3081    1.019297e+01     0.000420     0.091077                 210.50
3082    1.003796e+00     0.000420     0.091077                 210.50
3083    1.007951e+00     0.000630     0.136616                 221.29

[3084 rows x 4 columns]

### Splitting the data

In [4]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
print("TESTING DATA")
display(train)
print("TRAINING DATA")
display(test)

TESTING DATA

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1614        0.485686     0.000063     0.013662                 456.56
1508        0.126143     0.000147     0.031877                 429.58
904         1.009954     0.000420     0.091077                 865.27
495         1.108709     0.001659     0.359754                1136.11
1664        0.366195     0.000126     0.027323                 278.31
...              ...          ...          ...                    ...
599         0.171140     0.001680     0.364308                1385.02
1599        2.355534     0.000084     0.018215                 479.47
1361        0.081842     0.000252     0.054646                 640.84
1547        2.537942     0.000315     0.068308                 432.69
863         0.164118     0.000462     0.100185                 785.01

[2313 rows x 4 columns]

TRAINING DATA

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
994         0.338716     0.000189     0.040985                 855.65
2951        0.484057     0.000420     0.091077                 219.41
2331        2.543839     0.000189     0.040985                 111.00
1866        9.256815     0.000288     0.062388                 221.56
1203        0.456731     0.000063     0.013662                 525.78
...              ...          ...          ...                    ...
189         0.324675     0.001010     0.219041                 693.58
1054        0.490805     0.000084     0.018215                 600.53
1532        0.595047     0.002100     0.455385                 469.93
2430        0.735602     0.000063     0.013662                 132.89
2063        0.887056     0.000191     0.041440                 123.37

[771 rows x 4 columns]

### Training and testing the model

In [5]:
model = IsolationForest(contamination=0.01,random_state=101)
model.fit(train)

y_pred1=model.predict(test)
acc=(y_pred1==-1).sum()/test.shape[0]
print("The Accuracy of the anamoly detection unit (Isolation forest) is", (1-acc)*100,"%")

The Accuracy of the anamoly detection unit (Isolation forest) is 99.09208819714657 %

In [6]:
model=OneClassSVM(nu=0.01)
model.fit(train)

y_pred2=model.predict(test)
acc=(y_pred2==-1).sum()/test.shape[0]
print("The Accuracy of the the anamoly detection (One Class SVM) unit is ", (1-acc)*100,"%")

The Accuracy of the the anamoly detection (One Class SVM) unit is  97.4059662775616 %

In [7]:
model = EllipticEnvelope(contamination=0.02)
model.fit(train)

y_pred3=model.predict(test)
acc=(y_pred3==-1).sum()/test.shape[0]
print("The Accuracy of the the anamoly detection (Minimum Coeriance Determinant) unit is ", (1-acc)*100,"%")

D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:647: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn("The covariance matrix associated to your dataset "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.602543456437004 > -52.639300304994727). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-51.553181757204079 > -51.620887623625833). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.601251323225277 > -53.178209041155775). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.308609186706590 > -54.613121105127163). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.292174385046174 > -53.029643054299058). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.098855135023292 > -52.113041294487836). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "

The Accuracy of the the anamoly detection (Minimum Coeriance Determinant) unit is  98.70298313878081 %

D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-51.341144221139032 > -53.096291668874791). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-51.610512422051613 > -51.673939825575324). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-51.199874081869112 > -54.934212469001679). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.579992962063635 > -53.682541897535899). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "
D:\Users\danis\anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:166: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-52.429120150900587 > -54.649077738610266). You may want to try with a higher value of support_fraction (current value: 0.501).
  warnings.warn("Determinant has increased; this should not happen: "

In [8]:
print("Isolation factor has an higher accuracy than the others, so we will use Isolation forest for the remaining user transaction.")

Isolation factor has an higher accuracy than the others, so we will use Isolation forest for the remaining user transaction.

In [9]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)

<ipython-input-9-8d22b4d3fdd8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-9-8d22b4d3fdd8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [10]:
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x53b44ca1f6ce0e8712052a7fc9fb5475592badea1e77...,4886216,1515602909,1/10/2018 4:48:29 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x2791c6da7e712e4b753b7b16ccfcfed61b49c13e,0.043608,0.002583,0.560124,1248.99,-1
1,0xb305e09d6174628dcf2468ca2e4195e6899a6e89836b...,5893188,1530545766,7/2/2018 3:36:06 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xa603f8d47cf40f7e94f6ebd53683e75654076790,0.094161,0.003780,0.819693,476.58,-1
2,0x66aa15ffd00b504d2c3bafa1634569191408b39dc240...,4891232,1515683166,1/11/2018 3:06:06 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xb95cda1788f72dcb67f8695ef2951e7709cf2026,0.095879,0.003337,0.723584,1139.32,-1
3,0x0af7936edc68b89f3aa8bd092e280bf0c39084fc2495...,4859147,1515171755,1/5/2018 5:02:35 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xfc044f072406702a1e1183ae5477c857b14d56ce,0.119643,0.002940,0.637539,967.13,-1
4,0xa65757bc258b6ae3623ca3623cd4ff6a77b26f6e50c6...,4886585,1515608415,1/10/2018 6:20:15 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x7a9b31dd72cad9bccb3bc689dd99d6698726eb70,0.220320,0.002583,0.560124,1248.99,-1
5,0xb62c36a5427a34445b63ba18f76f93dd5bc99e6544ee...,4858903,1515167713,1/5/2018 3:55:13 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x00ed4b541a2d99b98c8bb1cf6597f888d072a2d8,0.234831,0.002671,0.579250,967.13,-1
6,0x4d161b5793267695a7e8d44e720a2bc8c587307b3612...,4859194,1515172458,1/5/2018 5:14:18 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xdada4519b0a602d174c0fd945c1e4fa3acc6c16a,0.294702,0.002940,0.637539,967.13,-1
7,0xa61c28743ba7806c252ff7260c11a92dcb963ab5cbd0...,4859200,1515172518,1/5/2018 5:15:18 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xdada4519b0a602d174c0fd945c1e4fa3acc6c16a,0.298586,0.002940,0.637539,967.13,-1
8,0xd2bfe9fd38d976b024b352d54c718e5774ca45e2dcc5...,5886493,1530447902,7/1/2018 12:25:02 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x2a284aa1ca4689a477f4dcc5add98ed38079a1f9,0.367700,0.002520,0.546462,451.95,-1
9,0x5d82a7705d42f63de972f52dcd45bfc122cceee31046...,5893178,1530545643,7/2/2018 3:34:03 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x8389454d613788a448410b7e7d8d6cb3fa9995ec,0.370211,0.003822,0.828801,476.58,-1
10,0xb691afe4789ff631dba7617c2f18c92d2005d2361500...,4891608,1515689029,1/11/2018 4:43:49 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xdf047b2feec6ef6882a930e2220a497030903cad,0.463661,0.002499,0.541908,1139.32,-1
11,0x64e7761d739763311d8e5bcba19a48f6df9a216e8c08...,4859140,1515171628,1/5/2018 5:00:28 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x44d7d54dc5cc9fefda0e35de2e3ca56dca4e0637,0.598214,0.002940,0.637539,967.13,-1
12,0x13c7b58e35261cd969a907ae7ff7850a3d68815553b3...,5893136,1530544991,7/2/2018 3:23:11 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x62969076ee49acc69a2aec8fba2487f33c84c13e,0.618557,0.003822,0.828801,476.58,-1
13,0xab81a726b72842ae4a095d3defdcc4d91e3932600d05...,4858491,1515161213,1/5/2018 2:06:53 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x2e5891e4f91c4a55e836482864ea10d369dc39cf,0.767913,0.002302,0.499145,967.13,-1
14,0xbf764bb5436d55c6563caccbf8b582009a2dfc79c230...,4859122,1515171401,1/5/2018 4:56:41 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xcd225e71e7f5c13f8ec7b554ef43ed617d2bcaba,1.217360,0.002940,0.637539,967.13,-1
15,0x95a25bf4c6abf85c9485b7da64bcffa2da1fb0a07206...,4858984,1515169027,1/5/2018 4:17:07 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xf4293d2bfb407ca8a51b2d03eb350cdd3cf08001,1.520236,0.002940,0.637539,967.13,-1
16,0x52f171d301687185ecf955a65046b8a73f79e0821759...,4875675,1515434283,1/8/2018 5:58:03 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xfdb6b529312aac97602cf6ab669b20ab3a7f7dfb,2.147791,0.002415,0.523693,1136.11,-1
17,0xcf7d0a00e71e811bfb22c3e6905c56fb948d784a31f3...,4885567,1515592614,1/10/2018 1:56:54 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x9f7a6591b2ee9afd45febd5413eb5ee55f27e5d1,3.088803,0.002016,0.437170,1248.99,-1
18,0x5930044854a5a90b8c7099cb3081ad132ca51159ee38...,4875491,1515431383,1/8/2018 5:09:43 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x9f7a6591b2ee9afd45febd5413eb5ee55f27e5d1,3.088836,0.002289,0.496370,1136.11,-1
19,0x01dbf37b92903fb7a26ba0448b842845d0e6faad82b4...,4858726,1515165055,1/5/2018 3:10:55 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x7d9cbe2ebe05f1c3591c166ab50cfe616c060e93,4.089980,0.002520,0.546462,967.13,-1
20,0x8f369d89836e300fce806b468fe0221828bc5da29573...,4880259,1515507426,1/9/2018 2:17:06 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x9f7a6591b2ee9afd45febd5413eb5ee55f27e5d1,4.810005,0.001781,0.386166,1289.24,-1
21,0x44a78530f64e0355709cd2c40f03ce0d36832a7dad58...,4863863,1515247918,1/6/2018 2:11:58 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xdada4519b0a602d174c0fd945c1e4fa3acc6c16a,5.786033,0.001680,0.364308,1006.41,-1
22,0x97e911f20a0b951b725caae264e82a99ce2c38246dee...,4777492,1513957787,12/22/2017 3:49:47 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x26f2d14cb7a571e77194ef814512a62ca40df08c,14.849788,0.000840,0.182154,657.83,-1
23,0x742273b29031d50fbb134bb5f32cc0355e412f267930...,8540840,1568371392,9/13/2019 10:43:12 AM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x6464981c56491b8758b65bffab319ca2f44fc827,15.408176,0.000692,0.149991,181.56,-1
24,0xde3068021e237aa3c11a6c652075e3dbb783a023a44c...,8007905,1561207073,6/22/2019 12:37:53 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x94cf57752d633636bc766905c16efa61a321b861,17.380315,0.000147,0.031877,309.41,-1
25,0x10a1d3abe8d610fe04261fa082a78d34394b66768528...,6733901,1542636414,11/19/2018 2:06:54 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0xcbc48e128d90836bb0fd73fda826dfacb80a06c3,18.085232,0.000265,0.057379,148.22,-1
26,0x1c3d7f58a95b4da708429e48db3886b8024d90058551...,6873068,1544619775,12/12/2018 1:02:55 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x7c35ffc83144fc1b7c3b9b429c3a41726953a4c9,18.164352,0.000174,0.037720,90.52,-1
27,0xf1028d7bcee97cf6763dc005714fd2be0b54bc8363b8...,6873325,1544623125,12/12/2018 1:58:45 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x05cb89d5d743763a57344ec0b6a23ffa8dd520b6,19.457113,0.000189,0.040985,90.52,-1
28,0x068f2b3ed588dbf1cfb936b4d45dacc48f0cafc4fcaa...,8476205,1567500059,9/3/2019 8:40:59 AM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x11e3a81b648173ad78cf0fb99456cdfd20175c47,22.735208,0.000210,0.045538,179.13,-1
29,0x1ff3ffaa722011fd4ddbe3652e0502861e466916ebe3...,7215736,1550072614,2/13/2019 3:43:34 PM,0x0067f95a79c3c404a9d128168ddfdf3cb70c0852,0x8a98cf4c776ea1bc3788aede0e93e43531595c21,44.514799,0.000265,0.057379,122.31,-1

## Ethereuem Address 2
### 0xf1Cf296C11d3b010E6dd3D48B6C5AaeD613E96f1

In [11]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\2_0xf1Cf296C11d3b010E6dd3D48B6C5AaeD613E96f1.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x43c312c34a764e39ecccb2e2e1942f89fbf3c53a872c...,5164321,1519719165,2/27/2018 8:12:45 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x12158ec38b398631fbed34a8faedb988527e5323,0.010000,0.000168,0.036523,871.58
1,0x28299a1d7f725289c010635f649f8b1ce87313488fe2...,5164347,1519719562,2/27/2018 8:19:22 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x6dbdd40dd86753c623dbfb7c09e8005beaf5617a,5.000000,0.000168,0.036523,871.58
2,0xcbc448bcaf85c5da4d1dc630f24014a440b1f6da2d94...,5164349,1519719588,2/27/2018 8:19:48 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x0066c0c37afe770f4378cd8ce744a8106ad87f36,0.984009,0.000168,0.036523,871.58
3,0x93c13ff7248608b15564e82122692a2346aab68e510d...,5164349,1519719588,2/27/2018 8:19:48 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xd0a2bfe251927120700420a5931b2c5a048c9349,2.156282,0.000168,0.036523,871.58
4,0xc274637b51acd42689d1549bbb9d016ac0a0e26d3f69...,5165447,1519735682,2/27/2018 12:48:02 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x899871a36627a2366f31227ba19c7d48206b1ec9,1.244525,0.000168,0.036523,871.58
...,...,...,...,...,...,...,...,...,...,...
3153,0x8049fb2179776ae1e4ba1cd007a3311de6a890a7c780...,8577064,1568858698,9/19/2019 2:04:58 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x33af2637f6efc03cf55b290a160b358e6660984c,4.800000,0.000416,0.090345,221.29
3154,0x678877d84010290545d82cea4f75b829fa6a204a7b06...,8578873,1568883513,9/19/2019 8:58:33 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xcb15d22722b61ee78756fb21ca6ea3752e055104,15.000000,0.000462,0.100429,221.29
3155,0xfaa2234a8c61f3a4ccb7e6872c875d7da64a3ca7398c...,8580144,1568900658,9/19/2019 1:44:18 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x426140b650db732e9fcdc382e61ea139d0646a37,0.987000,0.000462,0.100383,221.29
3156,0xc2ce91df2f602090e6657c9d25853ce6148ff6de94e2...,8580144,1568900658,9/19/2019 1:44:18 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xf999d68aa62837126eb5491fd6ffb46d8aafb7a4,1.802546,0.000462,0.100383,221.29
3157,0x4dfa83e2364fed8b59809e81488d30c0c3101892333d...,8584557,1568961032,9/20/2019 6:30:32 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x22e5e05c484c4dc3f4937173ad09105700ff749a,9.960000,0.000420,0.091258,NaN

### Pre-Processing

In [12]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           0.010000     0.000168     0.036523                 871.58
1           5.000000     0.000168     0.036523                 871.58
2           0.984009     0.000168     0.036523                 871.58
3           2.156282     0.000168     0.036523                 871.58
4           1.244525     0.000168     0.036523                 871.58
...              ...          ...          ...                    ...
3152        2.455581     0.000483     0.104946                 210.50
3153        4.800000     0.000416     0.090345                 221.29
3154       15.000000     0.000462     0.100429                 221.29
3155        0.987000     0.000462     0.100383                 221.29
3156        1.802546     0.000462     0.100383                 221.29

[3157 rows x 4 columns]

### Splitting the data

In [13]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
384         5.239803     0.000042     0.009131                 486.25
2773        3.200000     0.000231     0.050192                 264.71
2875        0.012034     0.000105     0.022814                 333.76
2261        1.544510     0.000046     0.010042                 131.56
323         4.690377     0.000042     0.009131                 557.57
...              ...          ...          ...                    ...
599         2.411215     0.000021     0.004565                 494.96
1599       32.200000     0.000105     0.022827                 499.06
1361        4.265136     0.000210     0.045654                 608.23
1547       27.688654     0.001197     0.260228                 467.19
863         0.865681     0.000079     0.017180                 683.02

[2367 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1515        2.800000     0.000021     0.004565                 441.75
2621        1.371271     0.000063     0.013693                 171.90
2228        0.018913     0.000126     0.027386                  86.39
45          0.934086     0.000168     0.036523                 869.87
2850        3.000000     0.000063     0.013689                 309.41
...              ...          ...          ...                    ...
1414        6.231441     0.000067     0.014662                 494.53
2281        6.222247     0.000099     0.021470                 137.30
288        40.997408     0.000063     0.013696                 555.55
1338        6.007375     0.000126     0.027392                 590.53
37          1.984000     0.000418     0.090777                 869.87

[790 rows x 4 columns]

### Training and testing the model

In [14]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  99.74683544303798 %

<ipython-input-14-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-14-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [15]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0xa8565e73916ee6aaa186d56f100fec789efc4a2fcb9e...,5697243,1527600561,5/29/2018 1:29:21 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xc61266f5fb3169b8ee3a05e7cc342ece37cf2a8c,0.010000,0.002100,0.456540,566.59,-1
1,0x735c730db2f4b5025ceb4c700a8778249cea5eb60f03...,5786832,1528970575,6/14/2018 10:02:55 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xf1db880a944c51615cfd6901cd59f79721549307,0.080000,0.002100,0.456540,519.83,-1
2,0x787cde595b76dbcc1af13c90597c13188d0776c49ba3...,5692632,1527530493,5/28/2018 6:01:33 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x95c9393f89bec731e37fff36f4faeb9b16089a75,0.741738,0.002100,0.456540,512.03,-1
3,0xaf9248429052f3cf1bbdc81823cc07d8b28d4322ac44...,5692322,1527525702,5/28/2018 4:41:42 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x27103cca2264023e00eaa59da3b0ae627a6b1cd5,0.944129,0.002100,0.456540,512.03,-1
4,0xa6df9a8b2bf96e1c12e6ee7d5bc5c5f31a9a5c1b4af9...,5786819,1528970392,6/14/2018 9:59:52 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x6368158de5fbae1e5c76b6c10b7edf678543b0f5,1.298064,0.002100,0.456540,519.83,-1
5,0x1f2b6a06a4d1d2828e798d118f2e6607693458bc97f1...,5886087,1530441859,7/1/2018 10:44:19 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x971f42e3092c378044655b5ff888976a8453c878,1.859854,0.002100,0.456540,451.95,-1
6,0x8097c3e45d6353b22bd1e0938e816bcb03ecbf5b0c08...,5692620,1527530346,5/28/2018 5:59:06 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x787e38c6bff58cc8931bbedc8a7b48f3ce1c6d0d,2.235244,0.002100,0.456540,512.03,-1
7,0x873d957582c155e16ffeb5a131b4444fc799fdf003c1...,5881318,1530371336,6/30/2018 3:08:56 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x896087db4330e162f1fd99bf4e065822c55f009e,2.943143,0.002520,0.547848,453.42,-1
8,0x1d7a276e0c54cec2d2458de5690d3b618e80c3a7199f...,5891521,1530521095,7/2/2018 8:44:55 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xfd157dfd5a283403b3a5469cc21c67ce7637b679,3.973037,0.001995,0.433713,476.58,-1
9,0x1f8ec46766febcd3e3a9c7f8a8016c75a27c6a1cf639...,5787034,1528973715,6/14/2018 10:55:15 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x7ef7c2ca845c70a557401136be1207e52d55e447,4.042748,0.002100,0.456540,519.83,-1
10,0x4ebd3b0305d7b2e0f70400db937576267e41cf5ce20c...,5787040,1528973831,6/14/2018 10:57:11 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xd1bb83b75ccaed33116b5f394e92f42aabf72051,4.532000,0.002100,0.456540,519.83,-1
11,0x18a111ea26d93fd095eaf52b9af8dbb0cc70ec2f997c...,5692354,1527526204,5/28/2018 4:50:04 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x15185019a6cd6518ebd6683d107742e7da26a534,6.490440,0.002100,0.456540,512.03,-1
12,0x8d356fb242efda2f578221f34449051a700d92ad28e6...,5692530,1527529045,5/28/2018 5:37:25 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xa2babf6a6a1e201ef95baefe4535e5cc15a2a62a,6.567209,0.002100,0.456540,512.03,-1
13,0x67be56957aeb50011fe7a8f50984ddec1ce3903391c0...,5896457,1530594021,7/3/2018 5:00:21 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xf273a850484ae92c4210c97ea521e35c968b633a,10.000000,0.002966,0.644817,461.95,-1
14,0x671ce3a4defc4725d9aad6143717e64f215abb14867a...,5893017,1530543363,7/2/2018 2:56:03 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xf273a850484ae92c4210c97ea521e35c968b633a,10.100000,0.006067,1.318944,476.58,-1
15,0x275700141484a07705b9759bf11e613eb712d30d73c5...,5786805,1528970201,6/14/2018 9:56:41 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x2cf7b82b0336506c02b8c05f9c2fa9142f41601d,11.957988,0.002105,0.457649,519.83,-1
16,0xc0b12df17ef71407dbd941880514e6116f9649ae373d...,5692625,1527530385,5/28/2018 5:59:45 PM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xed5301c542146c57ee2d9b1d17fb2e788c9fc301,30.805678,0.002100,0.456540,512.03,-1
17,0xd0968377261287fb54b89b7f3c0531fb7f56c4f3315e...,5896922,1530600824,7/3/2018 6:53:44 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x85ad88f2ebe39711863957bd0e917702b16e04f2,77.319265,0.001680,0.365232,461.95,-1
18,0x986dc62cf4c839b726019089f156fac80bc8001171fd...,5960661,1531541415,7/14/2018 4:10:15 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0x072225020fd39ea6d0608a71fda5b4ee2ffc7135,311.320000,0.000840,0.182616,433.74,-1
19,0xf8a9e5fc0b0a5c276b98bc22845365d418116c87cac2...,6115367,1533802831,8/9/2018 8:20:31 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xfc2c5867ad9d7cc288fb3829445da3c906e290a4,348.200000,0.001260,0.273924,363.51,-1
20,0xd22e0328b89c50b58c040f212aaf2e7d85d9fe6a0f59...,7808463,1558512663,5/22/2019 8:11:03 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xac2b003a903bec44f37d0cfd3fda3e803ffdc428,800.000000,0.000362,0.078710,243.46,-1
21,0xc571093ccba077867010450b7b1ad48ab4d4fff67c6f...,5712138,1527829767,6/1/2018 5:09:27 AM,0xf1cf296c11d3b010e6dd3d48b6c5aaed613e96f1,0xac2b003a903bec44f37d0cfd3fda3e803ffdc428,1000.000000,0.000252,0.054785,579.01,-1

## Ethereuem Address 3 
### 0x7D8eEc47d19bF4AD805CcA67a6701611a06ed151

In [16]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\3_0x7D8eEc47d19bF4AD805CcA67a6701611a06ed151.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0xc5d14895dfd9d4f8283119d1f3cfe1221c0b1356ed71...,6881487,1544739316,12/13/2018 10:15:16 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,0.045000,0.000151,0.032854,86.39
1,0xb7f62c1f74155d1c09a44c2f783e2246c1d238150e7f...,6881643,1544741543,12/13/2018 10:52:23 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,0.002000,0.000143,0.031029,86.39
2,0xae4288f9499c99eca596e9a712550090f51521602224...,6881783,1544743413,12/13/2018 11:23:33 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,19.591215,0.000097,0.020990,86.39
3,0x400d89c0b364f1b5677956c8566dcf9d7e3dae8b12b5...,6881902,1544745082,12/13/2018 11:51:22 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,236.635115,0.000168,0.036505,86.39
4,0x0f9660e249a864dc5d791cba24c554bc5513dcb478c8...,6884388,1544780486,12/14/2018 9:41:26 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x70ea255bac9ae37a53380f1d37c367ed024ade13,0.506612,0.000210,0.045631,83.90
...,...,...,...,...,...,...,...,...,...,...
3516,0xf106a6d77999e9a11541b8d0077b6817f0dd7578cadf...,8582451,1568932197,9/19/2019 10:29:57 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x967c35696749647d27a4cd7679ee4c158b4160b7,2.165671,0.000326,0.070850,221.29
3517,0x8851ca7cd2b4341529ca7b6584a8e3a1dce69954ba8f...,8583415,1568945344,9/20/2019 2:09:04 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x5e41060acc590cb77f7cd2478436ef99797110a3,5.718073,0.000756,0.164294,1240.14
3518,0x8a6ca4a76f39bdb8bb4152e3cf018cb8e31b8dd70129...,8585171,1568969411,9/20/2019 8:50:11 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xd510287f8b5e9931a618e5de6939b1be604ff688,1.000000,0.000756,0.164294,216.88
3519,0x7730312f4461d62247fd260df3b9eae77e7301d35c99...,8585218,1568970049,9/20/2019 9:00:49 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x5398365cf2be6ce25151abefa0cd29914642560a,2.876773,0.000756,0.164294,623.91
3520,0x5d0dc4f04420ab3a6837eb3ec647f5559726c4de8050...,8585235,1568970228,9/20/2019 9:03:48 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x5398365cf2be6ce25151abefa0cd29914642560a,0.944438,0.000756,0.164294,204.75

### Pre-Processing

In [17]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           0.045000     0.000151     0.032854                  86.39
1           0.002000     0.000143     0.031029                  86.39
2          19.591215     0.000097     0.020990                  86.39
3         236.635115     0.000168     0.036505                  86.39
4           0.506612     0.000210     0.045631                  83.90
...              ...          ...          ...                    ...
3516        2.165671     0.000326     0.070850                 221.29
3517        5.718073     0.000756     0.164294                1240.14
3518        1.000000     0.000756     0.164294                 216.88
3519        2.876773     0.000756     0.164294                 623.91
3520        0.944438     0.000756     0.164294                 204.75

[3521 rows x 4 columns]

### Splitting the data

In [18]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1921        0.483918     0.000126     0.027382                 267.42
482         0.142608     0.000168     0.036505                 119.46
3008        0.153849     0.000109     0.023731                 208.62
50          1.165000     0.000126     0.027379                 116.43
579         0.576848     0.000126     0.027379                 144.40
...              ...          ...          ...                    ...
599         0.028814     0.000210     0.045631                 149.04
1599        2.390392     0.000531     0.115446                 248.64
1361        0.225094     0.000126     0.027379                 161.29
1547        3.754528     0.000042     0.009126                 195.83
863         0.264601     0.000084     0.018252                 139.46

[2640 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
2429        0.297564     0.000042     0.009127                 306.43
2576        0.017618     0.000042     0.009127                 228.14
256         1.034316     0.000210     0.045631                 129.74
747         1.403131     0.000210     0.045631                 134.42
60        178.712885     0.000252     0.054757                 118.36
...              ...          ...          ...                    ...
1800        0.203778     0.000084     0.018252                 249.61
1812       59.363975     0.000084     0.018252                 251.49
2190        0.719834     0.000164     0.035597                 309.41
1379        0.755200     0.000126     0.027379                 168.24
291         0.370545     0.000084     0.018252                 124.85

[881 rows x 4 columns]

### Training and testing the model

In [19]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  99.09194097616346 %

<ipython-input-19-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-19-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [20]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0xee7b61923a91fbf48b747851fe691fbf4527ec8b61fb...,8273272,1564776507,8/2/2019 8:08:27 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x9a36625a04d01bcbae364f508bc8076ac551e8a8,0.248507,0.001433,0.311515,217.70,-1
1,0x0e3c5193730cbdb3b3bbd179d522bcc4d0f16d65419f...,8581612,1568920755,9/19/2019 7:19:15 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x1a7c143e0ff6d2b9a746c1787fdd9c3e9161bfe6,0.460880,0.001364,0.296408,221.29,-1
2,0x8bc18dc3d6de02a39d34cf9888accc5fda8be954f5b6...,8130526,1562856201,7/11/2019 2:43:21 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x1cb7d78b4a99a4346f93729917633c774d401a55,0.998517,0.001348,0.292991,268.56,-1
3,0x4fc96aac3c90d96a99075e3ddfe7251395753af69c28...,7043013,1547132733,1/10/2019 3:05:33 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xbffe2a090f822f046ca773cc4a5a61f58d91e7ff,1.357049,0.001260,0.273785,127.96,-1
4,0x6b477e26bd59ea8f5a21bec50d38fe80d0b7dad2cf03...,7109284,1548168259,1/22/2019 2:44:19 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x4bf9c5c42dde8005b15e1832ef1008bc5120f284,1.552590,0.001722,0.374173,119.12,-1
5,0x47a3775626170ef120e24b990364849b1b097418496b...,8572837,1568801430,9/18/2019 10:10:30 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x3331c2f51c8dfee751965dcd78156796b9173194,1.961696,0.001941,0.421907,210.50,-1
6,0xf862ba65a242cbf9153235515fd30174ae591c507e42...,8039310,1561629456,6/27/2019 9:57:36 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x98e8ac951382732e9d0e5d4d4aead51083b98124,1.999000,0.001384,0.300704,294.07,-1
7,0x860dc718d6c5b577cca8ab758fe3dafec26663cf7425...,7933082,1560195277,6/10/2019 7:34:37 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x2500fb34abe74c06b2291c22451b1bf7c6059dfe,2.999000,0.001318,0.286384,247.96,-1
8,0xeae75836b23ce2dbf5d767d16d78f3158aacba2b47ad...,8572833,1568801410,9/18/2019 10:10:10 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x7380a4fa7edca82a983ea2f22befd02e7b9575b4,4.774467,0.001210,0.262870,210.50,-1
9,0x8b90c3df20e1728b87f4179729da014225b248241e7d...,8163223,1563298289,7/16/2019 5:31:29 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x2c2d258b99684013bb0400c0c7616212413bfe74,18.947840,0.001108,0.240790,198.71,-1
10,0x20f301ef18932b6b1346c493bf70cc4ec733e1fdaa94...,8573281,1568807877,9/18/2019 11:57:57 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xaf59de702bdc4b3482672d799c6b94a425d45623,48.580110,0.001134,0.246441,210.50,-1
11,0xf2abc96889dccae9cdb3e673455304d6fdc1db2d89a6...,8027634,1561472197,6/25/2019 2:16:37 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x30650edd82511166146d6f75611a12f1870f8951,60.000000,0.000840,0.182549,316.53,-1
12,0x59af1c3f68567962550380112fd5dd930b76dd7ac912...,8131804,1562873354,7/11/2019 7:29:14 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x75ca8f420b1ae99ceaf466946ec7858028134b07,75.026402,0.000842,0.182992,268.56,-1
13,0xca546be3c2046362d5748b61663ed7e93b4a4bf2c99c...,7937957,1560261778,6/11/2019 2:02:58 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,96.375396,0.000840,0.182549,245.16,-1
14,0xc9912cb9daba8aef815e699e2a1f963b49b94228fb9a...,8181779,1563548953,7/19/2019 3:09:13 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x2ffe2f68d1ab4557f4778a67d16400df3d1e508f,96.999000,0.000840,0.182549,221.28,-1
15,0x80be2693b5aff7c8036df0f9f86162cd7b184b8e9a5d...,7265934,1551098513,2/25/2019 12:41:53 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xc169ed40f362a3f8facc60ab58d330644cf98d8a,99.999000,0.000790,0.171578,139.02,-1
16,0x4c3ca5dde80bb30e64bea2ce581ed98b784b091b0380...,7847946,1559045295,5/28/2019 12:08:15 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0x2ffe2f68d1ab4557f4778a67d16400df3d1e508f,141.999000,0.000336,0.073009,271.45,-1
17,0xd5ad77047b36c7d183e3e17617683aea0490403139dd...,6914163,1545211866,12/19/2018 9:31:06 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,146.141380,0.000336,0.073009,100.63,-1
18,0xedd3f4f5a935d36154bedfa845fe5214172b1846f0b0...,7193521,1549638191,2/8/2019 3:03:11 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,153.792234,0.000353,0.076660,119.49,-1
19,0x2e7f2408fdf93b08e1cc648306241c5c40ea3bd6fc97...,7747154,1557684618,5/12/2019 6:10:18 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,176.222561,0.000042,0.009126,188.14,-1
20,0x92ed473903efda6214ec482142ae283f548166a22b8b...,6931388,1545466256,12/22/2018 8:10:56 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,178.712885,0.000252,0.054757,118.36,-1
21,0x66ef26d757ba3bbcbe39b9ff1e6710e5085601f0f75c...,8152756,1563154872,7/15/2019 1:41:12 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,184.696082,0.000168,0.036510,228.14,-1
22,0x506c1d6b58d0604e4f7bddf9c0bb44adc3f7d6352115...,8179974,1563523823,7/19/2019 8:10:23 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,195.498379,0.000084,0.018255,221.28,-1
23,0x853470550c8fb4e95ae4210fbf70336ec1c9c8d432fb...,8167035,1563349805,7/17/2019 7:50:05 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,199.834125,0.000714,0.155166,211.29,-1
24,0xbbbd251b58577cf9d35b5123a1c8f6eb31717ff0fdc7...,6903410,1545053465,12/17/2018 1:31:05 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,226.354899,0.000210,0.045631,95.44,-1
25,0xce2400b4ad49c3c87c14d203d5ae94a39d9d97ea85a0...,7398748,1552991458,3/19/2019 10:30:58 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,228.864497,0.000084,0.018252,139.46,-1
26,0x400d89c0b364f1b5677956c8566dcf9d7e3dae8b12b5...,6881902,1544745082,12/13/2018 11:51:22 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,236.635115,0.000168,0.036505,86.39,-1
27,0x363dfadf010f44d5a27e01a654938e89f3f6d94fdd46...,8444394,1567072826,8/29/2019 10:00:26 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,256.876215,0.000210,0.045637,168.95,-1
28,0xcc843166d19fa16dcb3b81cd7e009221e572c30d404b...,7489633,1554217919,4/2/2019 3:11:59 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,308.233389,0.000462,0.100388,164.93,-1
29,0xff03756da158bdc0fced1d811bc128efa23b851071f7...,7764257,1557914452,5/15/2019 10:00:52 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,317.682071,0.000378,0.082136,248.64,-1
30,0x17dfa8c2640f91ae643a4fd0d9206a33f5a3f6c3e16d...,7942575,1560324050,6/12/2019 7:20:50 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,334.230107,0.000126,0.027382,263.05,-1
31,0x58f435180f77cb3928cb4834bb7ce38913b4c06491c6...,8360961,1565951427,8/16/2019 10:30:27 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,366.067902,0.000053,0.011409,185.41,-1
32,0xd8e2d5305fbffaaf1dc82230d104b56010607307de22...,7010476,1546630235,1/4/2019 7:30:35 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,384.244663,0.000084,0.018252,156.04,-1
33,0x4c72906eb7111d07d5481d6330f0e1666f344f2d0191...,7707994,1557155573,5/6/2019 3:12:53 PM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,389.797458,0.000231,0.050194,173.70,-1
34,0x049065541efcf006a79ffdc51364965877096461c32b...,6955957,1545824518,12/26/2018 11:41:58 AM,0x7d8eec47d19bf4ad805cca67a6701611a06ed151,0xa7b790bcea75a61e3b64902e7816f912c573a55d,399.828363,0.000139,0.030116,132.61,-1

## Ethereuem Address 4 
### 0xCac76b259AD18A269BE1987c0E8a07A2B855f7b6

In [21]:

dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\4_0xCac76b259AD18A269BE1987c0E8a07A2B855f7b6.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x0c2980546a819879ef1abb9d361b6f15d48f44eb6c94...,4393285,1508469994,10/20/2017 3:26:34 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.010000,0.000003,0.000685,303.08
1,0x878f68b275e9dcc69cdb1c26e14763648b67ecc490c6...,4393611,1508474450,10/20/2017 4:40:50 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.010000,0.000004,0.000822,303.08
2,0x7cbcb7ae687598f40dda690753674e30368468f29a4a...,4393656,1508475119,10/20/2017 4:51:59 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.010000,0.000063,0.013699,303.08
3,0x1243339d9d14ccd1501c93a285dafc0d1950c1192db2...,4393670,1508475359,10/20/2017 4:55:59 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.010000,0.000063,0.013699,303.08
4,0xf15d7a33f5f264af2072ba2bb1087f0ac2b2526c493d...,4393944,1508479324,10/20/2017 6:02:04 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.100000,0.000063,0.013699,303.08
...,...,...,...,...,...,...,...,...,...,...
4241,0xb3767cdef331664f8bd5771c52d9284c9882af59a50a...,8582280,1568929865,9/19/2019 9:51:05 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x8159b615bc97a11aeb8c61b450b474190d87933d,0.017052,0.000210,0.045749,221.29
4242,0x97ba7467c0d17d1bf65c199b2896db7653f58a82e74b...,8582289,1568929991,9/19/2019 9:53:11 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x8c0294bb0938175c2f8496fcf86e2375f347cdde,0.007646,0.000210,0.045662,221.29
4243,0xfaf938466779ee6de9adf6e46074a4c6684e674a6de4...,8582291,1568930055,9/19/2019 9:54:15 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x00966d286ae0fdbfa880cc98a289743984806acf,0.053444,0.000210,0.045662,221.29
4244,0x4f10458b01d9c42ae819c42fbbdce5e50e174fbcb4e9...,8582804,1568937069,9/19/2019 11:51:09 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x7d680fe8d2d54581a55a78c3c6627ff37a1b9b76,0.010401,0.000206,0.044840,221.29
4245,0x5008ba994c4859927c17065e0a73b107a3723af5be4e...,8582952,1568938928,9/20/2019 12:22:08 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xe26b769a019823c3828f03c1115fc59ae310cbb3,0.105474,0.000096,0.020983,23.06

### Pre-Processing

In [22]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           0.010000     0.000003     0.000685                 303.08
1           0.010000     0.000004     0.000822                 303.08
2           0.010000     0.000063     0.013699                 303.08
3           0.010000     0.000063     0.013699                 303.08
4           0.100000     0.000063     0.013699                 303.08
...              ...          ...          ...                    ...
4241        0.017052     0.000210     0.045749                 221.29
4242        0.007646     0.000210     0.045662                 221.29
4243        0.053444     0.000210     0.045662                 221.29
4244        0.010401     0.000206     0.044840                 221.29
4245        0.105474     0.000096     0.020983                  23.06

[4246 rows x 4 columns]

### Splitting the data

In [23]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
3427        0.050021     0.000055     0.012055                 302.17
182         0.020943     0.000002     0.000457                 296.82
2466        0.200141     0.000040     0.008596                 132.89
3264        0.007000     0.000105     0.022831                 272.21
3135        0.200434     0.000051     0.011014                 244.40
...              ...          ...          ...                    ...
4079        0.007045     0.000042     0.009132                 175.01
4171        0.051176     0.000210     0.045662                 181.19
599         0.100008     0.000130     0.028312                 619.04
1361        0.050127     0.000092     0.019956                 227.49
1547        0.050149     0.000091     0.019727                 195.67

[3184 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1330        0.100267     0.000045     0.009749                 224.62
665         0.050031     0.000063     0.013699                 457.65
2087        0.050006     0.000210     0.045665                 121.22
45          0.010841     0.000084     0.018266                 294.03
2962        0.010180     0.000064     0.013973                 243.46
...              ...          ...          ...                    ...
2067        0.050274     0.000052     0.011233                 125.83
3230        0.200173     0.000076     0.016530                 273.92
4085        0.007053     0.000029     0.006347                 175.01
508         0.050515     0.000021     0.004566                 393.82
1370        0.200004     0.000105     0.022832                 227.49

[1062 rows x 4 columns]

### Training and testing the model

In [24]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  98.7758945386064 %

<ipython-input-24-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-24-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [25]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x68d7f5bd00a460f408fecf280085ebbedbfa45c56e84...,5896510,1530594763,7/3/2018 5:12:43 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x433482e247948d3e2119eaf7abac4bdfc44aa34f,0.008738,0.003912,0.850597,461.95,-1
1,0xfeeba0d81622745b7d4efcbfd2ea81dd867f14921d2f...,6117145,1533829563,8/9/2018 3:46:03 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x21c0010ee5a97a5f67e972e760b5f3e6e62fc080,0.048973,0.002371,0.515513,363.51,-1
2,0xc1ae8eb6cf44a4a9b6f0366ec8edccae30bd72ff50f2...,4893484,1515718686,1/12/2018 12:58:06 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x433482e247948d3e2119eaf7abac4bdfc44aa34f,0.050005,0.000889,0.193317,1261.03,-1
3,0x35bb11807cda7664d2d4c5d17af2d0b8c80f9d10e3cb...,4893519,1515719228,1/12/2018 1:07:08 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x9d74d5b841a6019ddd36650337d2bdf6b0a5b0bb,0.050014,0.000473,0.102745,1261.03,-1
4,0xac09b15dffe683c3fa68f4085767a00c0ab9b16aa403...,5663288,1527082512,5/23/2018 1:35:12 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x433482e247948d3e2119eaf7abac4bdfc44aa34f,0.050029,0.000395,0.085919,577.01,-1
5,0xb156d155b15d9a262a412f1c14ad7ac8f01b75bcba38...,5965887,1531617084,7/15/2018 1:11:24 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x21c0010ee5a97a5f67e972e760b5f3e6e62fc080,0.051083,0.000790,0.171838,449.62,-1
6,0x49799c16ad384befdc42a7aefc8b56deeff40da9dde3...,5630837,1526584366,5/17/2018 7:12:46 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x433482e247948d3e2119eaf7abac4bdfc44aa34f,0.051339,0.000395,0.085919,668.38,-1
7,0x265fe3e10aff4d9aca80c4c4f4db0154aa84c8e9b305...,5895996,1530587019,7/3/2018 3:03:39 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xe26b769a019823c3828f03c1115fc59ae310cbb3,0.052113,0.001680,0.365316,461.95,-1
8,0xfc1e1f6b87912a2296caf32d9bbc4a4ce451d2c84726...,4731670,1513261900,12/14/2017 2:31:40 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x433482e247948d3e2119eaf7abac4bdfc44aa34f,0.055753,0.001580,0.343675,693.58,-1
9,0x7a602d4e0c9a3db8a5c3f6f79b35b390e493be6b7b9c...,4731350,1513257191,12/14/2017 1:13:11 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x9d74d5b841a6019ddd36650337d2bdf6b0a5b0bb,0.056051,0.001010,0.219647,693.58,-1
10,0x34e831a44ebf675e43b6ef7764cf6be68ba075fe7625...,4734495,1513305318,12/15/2017 2:35:18 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x6da2ae10be3c8698ec71b9a8c6b585d9af74482d,0.058776,0.000505,0.109823,684.27,-1
11,0x202ace304ca10428d2414804703d5c1853626b81263e...,6110729,1533735214,8/8/2018 1:33:34 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x7f9451608f206810ae7387a5394cb247805c2a1b,0.059176,0.001260,0.273987,355.57,-1
12,0x158b75ffef394b64678b4b5c5e912a20d9e4d1584798...,6115848,1533809931,8/9/2018 10:18:51 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x254b0590467a4b029e994ab90d8bef48d034cce9,0.059982,0.000987,0.214623,363.51,-1
13,0xc4b91e2f660de0be234627548e076d3306fe4e3d0fe0...,4730040,1513237747,12/14/2017 7:49:07 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.065310,0.000672,0.146172,693.58,-1
14,0x2bb1d89c0cda5706e2d1789e4f041693e5e7e433413d...,6110643,1533734035,8/8/2018 1:13:55 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.068322,0.001260,0.273987,355.57,-1
15,0x6e76e4f9727c90dd9bdc50c26f00618e238682957c66...,5913376,1530845113,7/6/2018 2:45:13 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x80d8c1752fc8ae936dddccfd2a07203e0aebfc2a,0.103463,0.001470,0.319652,469.93,-1
16,0xe914f30cb49d7c9f92e595d0351ae874f3be68d7095f...,6110779,1533736013,8/8/2018 1:46:53 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xfbcab0f8e0cdfdfbcad8bd498fbf6f30e3e262d6,0.104547,0.001260,0.273987,355.57,-1
17,0xf0189eb67e5d8c371351e681deaaa22027ee19b62cb1...,6110700,1533734811,8/8/2018 1:26:51 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xa21982d2b0038ec95c852f4b169f89b469f00638,0.109056,0.001260,0.273987,355.57,-1
18,0x5e132be36fd98e53f39b66db7d7142c2897ada399580...,4898715,1515802069,1/13/2018 12:07:49 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.133952,0.000263,0.057081,1385.02,-1
19,0xd91030287a1c19c327ea450b01918edcf24fa3c33e5d...,5893546,1530551108,7/2/2018 5:05:08 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.140033,0.002096,0.455732,476.58,-1
20,0xe95820b59640921991f68ab8c7ecc149b3f73b60bf22...,4730094,1513238619,12/14/2017 8:03:39 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.153963,0.000672,0.146172,693.58,-1
21,0x9ef9c71461cc6e3b78d2b486dec0a6dc06ec70fc5fa6...,4734517,1513305607,12/15/2017 2:40:07 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.183918,0.000505,0.109823,684.27,-1
22,0x8b077d1c16cb3292dfd068800a1a0dcb7ad91a8f6fc8...,6114625,1533791947,8/9/2018 5:19:07 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x1f38408bf112ab3b169522c26205a9d57b800da7,0.200557,0.000756,0.164392,363.51,-1
23,0xda1e021438c6601158a0cde326d377c200dc03f56da7...,5960989,1531546346,7/14/2018 5:32:26 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xe773f368a3a13456a83214ae89e9ab1017f33fda,0.202586,0.000525,0.114161,433.74,-1
24,0x8102cf669baaf520d196c7b4b6d367b323b4cc250782...,5960964,1531546002,7/14/2018 5:26:42 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xb3ef7b6e809f4421132f40f1d62796db904648e1,0.230742,0.000526,0.114438,433.74,-1
25,0x276f589b0c70790f6caf555cc8545e518ba98f3c1acc...,4730308,1513241875,12/14/2017 8:57:55 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.295538,0.000672,0.146172,693.58,-1
26,0x6e8a3be08503026433a5ada76062b8376ccfde22663c...,8165476,1563328419,7/17/2019 1:53:39 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x8ce3960a4fc7060e781586ab1278cd3bbc732bb3,0.304363,0.000420,0.091325,211.29,-1
27,0x07f0d802e3eae5213d8b88153dd774ceca5faa5ec6b0...,8165468,1563328287,7/17/2019 1:51:27 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.327249,0.000420,0.091325,211.29,-1
28,0x093c6bffeb3be24718731b075a940abb005dbf961a67...,6113333,1533773398,8/9/2018 12:09:58 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x00151c0ca7e60091ea5f2242e917494d329f8a06,0.344905,0.000420,0.091329,363.51,-1
29,0x3fe3abf29e4f6cbbafc78844ce596a649ad8f3d9d368...,6115820,1533809564,8/9/2018 10:12:44 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x00151c0ca7e60091ea5f2242e917494d329f8a06,0.347464,0.000987,0.214623,363.51,-1
30,0xca1846b416964d0dac36fff6e099bb33cea8ff5c2dea...,8572107,1568792182,9/18/2019 7:36:22 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xf6329b1493fe63c305ce3af07352101491eb6013,0.352576,0.000630,0.136987,210.50,-1
31,0x75d6f292323cc67a3ea364f2c60bd661c6d5d0f7c86b...,4731521,1513259675,12/14/2017 1:54:35 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.376996,0.000662,0.143843,693.58,-1
32,0xedc5773641132e6bcca11167617c7578fc53016aa93f...,4731444,1513258581,12/14/2017 1:36:21 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,0.416643,0.000840,0.182658,693.58,-1
33,0x3486e504089aad80660be3b40b036ef97438910437ee...,6110745,1533735409,8/8/2018 1:36:49 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x00151c0ca7e60091ea5f2242e917494d329f8a06,0.930384,0.001260,0.273987,355.57,-1
34,0x53f59394bbd13a978a336da13e3a48370ea4772346e2...,6840260,1544151912,12/7/2018 3:05:12 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x254b0590467a4b029e994ab90d8bef48d034cce9,0.937490,0.000189,0.041098,93.61,-1
35,0xae8e4137d9acc22c4f4b15f047be6b3bb28dab3fb5d0...,8065156,1561977614,7/1/2019 10:40:14 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xffe2f7e069572833f98caca07cc6ff309150dc15,1.000244,0.000178,0.038756,294.17,-1
36,0x543a8a8bb7e7759af36ff193835dd4660e10a1548f12...,7866140,1559290353,5/31/2019 8:12:33 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x175552c8adebe6e05eea5f50cef8f54607201e81,1.000304,0.000207,0.045106,267.42,-1
37,0xea34d128138311995f997374adee044248a0e5b7422d...,6827246,1543964966,12/4/2018 11:09:26 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x68539694381803612867e65f5d465039086bb62b,1.000353,0.000151,0.032878,109.82,-1
38,0x21167fc8ddc0ed93152c95e1118369325cd3515b557e...,6438778,1538473016,10/2/2018 9:36:56 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x175552c8adebe6e05eea5f50cef8f54607201e81,1.000394,0.000246,0.053502,225.41,-1
39,0x10cb4ffe2a6f3e148e37399d5dfe142c8518cea7eebf...,6821909,1543888948,12/4/2018 2:02:28 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xffe2f7e069572833f98caca07cc6ff309150dc15,1.000699,0.000205,0.044476,109.82,-1
40,0x805ed7f24f32c10769b326137fa6112cc7bf3f4313c4...,8429994,1566879078,8/27/2019 4:11:18 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x1f38a52435d9ed7878a94a342cc131d56423092a,1.001133,0.000208,0.045206,187.17,-1
41,0xf3687889faac2334469401b954e308c0696ee55077b9...,8552094,1568523304,9/15/2019 4:55:04 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0x1f38a52435d9ed7878a94a342cc131d56423092a,1.003642,0.000210,0.045662,189.48,-1
42,0xa47d7aacce2d276a24053972ff7ad8313ffceee9ea85...,8092007,1562338932,7/5/2019 3:02:12 PM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xf74a81e00fc48c627153ba1e44da38e0d8b0aa28,1.111739,0.000420,0.091325,287.90,-1
43,0x4dca1c5170ea7fd52a4c93239d84d341630772e244a0...,4893535,1515719519,1/12/2018 1:11:59 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xeca14e56727eca9781f97caf9542cd2a6962f05b,1.185100,0.000473,0.102745,1261.03,-1
44,0x8ab305d499c429187d066ab74747aeeedb77f728a972...,7064275,1547461487,1/14/2019 10:24:47 AM,0xcac76b259ad18a269be1987c0e8a07a2b855f7b6,0xdc379a8c62a2ba38aa5f22f7f18acfb69adc20bb,1.206005,0.000152,0.033048,129.74,-1

## Ethereuem Address 5
### 0x491fe5F4724e642C90372B0B95b60c4aC8d13F1c

In [26]:

dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\5_0x491fe5F4724e642C90372B0B95b60c4aC8d13F1c.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x56543ac240598267d7460c0eaff1cacbf11b83995217...,6247803,1535736503,8/31/2018 5:28:23 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xf892003f065f52d181520cef187c1f9971512d5a,1.032400,0.000067,0.014606,281.66
1,0xba1b9eb9f44b47bd3c15c2462a8306b231bc16018ed7...,6271387,1536080347,9/4/2018 4:59:07 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x84261a911c032abfe88130ab56ebc5588f99efc8,0.024880,0.000053,0.011411,285.23
2,0x9218baa943aa565fca93b8f03e6e371b3e0c9a999b37...,6287493,1536312262,9/7/2018 9:24:22 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x6d3ea4ae8fa8ba006284c83fd5fa9f9c7de90c5b,0.896288,0.000094,0.020434,215.14
3,0xc7d528f0d033ec9265ccfa1227bb862afc5786493175...,6292620,1536387301,9/8/2018 6:15:01 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x4fc77498a7bddf4eebaa014051959a81d48c123e,0.020870,0.000063,0.013693,196.77
4,0xdf9d4a207355fda31a429162a9d987d124a7805b8b8e...,6299494,1536487927,9/9/2018 10:12:07 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x72f3203665781ab9bcfb33364f720171ab112412,0.995000,0.000105,0.022822,195.99
...,...,...,...,...,...,...,...,...,...,...
2202,0xf785449c40f82ad0d817b7fc94abe6f533b87b4110c8...,8580615,1568906905,9/19/2019 3:28:25 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x7e6723de3c2d667cc0d271e8c856da1ccaebd9d2,1.155600,0.000462,0.100416,221.29
2203,0x2668921f472e11d98fd64c261ba5a05cb2974327762e...,8582245,1568929254,9/19/2019 9:40:54 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x8668449d165178e750d4eb876f05ae738657f685,49.538593,0.000280,0.060751,221.29
2204,0x1f3242c550b31f57f693487d0f6cf390e746e83062bc...,8583920,1568952076,9/20/2019 4:01:16 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xd604da62ec7622f353f4e36e79fd3325cef63138,0.041400,0.000420,0.091287,NaN
2205,0xe691a94e2e9534d449046a9e6e1a36181d61975c8993...,8584697,1568962913,9/20/2019 7:01:53 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x6919af05154acc7826e3282b803466e778981af2,1.341900,0.000420,0.091287,NaN
2206,0xb756300534aab98b791c862060daee557b4f391eba58...,8585333,1568971619,9/20/2019 9:26:59 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xf0d83a559a40bdf8931d4ca2f0b8736dcb69c8b5,2.144009,0.000420,0.091287,NaN

### Pre-Processing

In [27]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           1.032400     0.000067     0.014606                 281.66
1           0.024880     0.000053     0.011411                 285.23
2           0.896288     0.000094     0.020434                 215.14
3           0.020870     0.000063     0.013693                 196.77
4           0.995000     0.000105     0.022822                 195.99
...              ...          ...          ...                    ...
2199        3.078591     0.000483     0.104980                 221.29
2200        0.200000     0.000441     0.095851                 221.29
2201        0.038000     0.000441     0.095851                 221.29
2202        1.155600     0.000462     0.100416                 221.29
2203       49.538593     0.000280     0.060751                 221.29

[2204 rows x 4 columns]

### Splitting the data

In [28]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1806        0.340000     0.000063     0.013693                 219.85
258         0.098000     0.000189     0.041079                  95.44
1111        1.037715     0.000252     0.054772                 243.46
1579        1.000000     0.000021     0.004564                 307.89
422         8.928000     0.000063     0.013693                 158.61
...              ...          ...          ...                    ...
599         6.493000     0.000063     0.013693                 107.21
1599        2.270000     0.000137     0.029668                 288.64
1361        2.000000     0.000420     0.091287                 272.21
1547        2.000000     0.000420     0.091287                 287.98
863         0.624000     0.000084     0.018257                 181.06

[1653 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1700          29.748     0.000420     0.091287                 198.71
969            0.600     0.000104     0.022548                 168.59
1503           0.100     0.000420     0.091287                 294.17
252            0.030     0.000063     0.013693                  95.44
50             0.038     0.000162     0.035145                 199.45
...              ...          ...          ...                    ...
1384           0.736     0.000031     0.006847                 309.41
1628           9.878     0.000063     0.013693                 275.41
1251           1.000     0.000021     0.004564                 241.10
230            1.070     0.000105     0.022822                  90.52
366            9.978     0.000063     0.013693                 133.49

[551 rows x 4 columns]

### Training and testing the model

In [29]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  98.91107078039929 %

<ipython-input-29-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-29-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [30]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x44a5fcf632280d7e2900d55171e4b7f01494faafc05b...,8573273,1568807817,9/18/2019 11:56:57 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x9dfbb9d94ea059723c3051b18418f7df1e95c09e,0.079767,0.000672,0.146059,210.50,-1
1,0xdafde98ee0bddf70cdb2367a72c0937ef5c343b908f2...,6799349,1543567128,11/30/2018 8:38:48 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x3522a59e374fd1478dc9bc4bbcad22f7c914d23c,0.379000,0.000630,0.136931,112.87,-1
2,0x7b29286f9244e6a64890a74c2fa060f4d54ecdd24e39...,8572263,1568794139,9/18/2019 8:08:59 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xf56a69e021695d6004f5cb1bb137cf2a3822b6ce,1.000000,0.000630,0.136931,210.50,-1
3,0xe2b533da483d923e1030717b89bfc4abc4be501d71b1...,8573303,1568808248,9/18/2019 12:04:08 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x9dfbb9d94ea059723c3051b18418f7df1e95c09e,1.693002,0.000630,0.136931,210.50,-1
4,0x01a8967af2c0bfc4371a3ef1f12ad195d71ffa37167c...,8573345,1568808789,9/18/2019 12:13:09 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x9dfbb9d94ea059723c3051b18418f7df1e95c09e,2.129008,0.000609,0.132366,210.50,-1
5,0x23145f23cc626d7061938de9c45849ed6b15a02dec2a...,8573639,1568812451,9/18/2019 1:14:11 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x9dfbb9d94ea059723c3051b18418f7df1e95c09e,2.852621,0.000630,0.136931,210.50,-1
6,0x877654eb5fecf7d11a63b0ad87f0d834b62521f543fb...,8571855,1568788899,9/18/2019 6:41:39 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x03004abd19e4391d7888dd2221fda75c1629f555,4.247000,0.000567,0.123237,210.50,-1
7,0x14de4de371da1f09d1a9afd2d5cf8a358e3cf4e5f8ea...,7043269,1547136934,1/10/2019 4:15:34 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xdb94a1aa7c4d0213cd0f81ba536a60adeac5960c,18.000000,0.000420,0.091287,127.96,-1
8,0x4ac6a2ef3a79bcffdb452425a6a5b0e65124e5f8036c...,7975389,1560767228,6/17/2019 10:27:08 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x50675af2f8eb634cbd6af6aa681910e1fb8232b9,19.108000,0.000420,0.091287,273.92,-1
9,0x63acd3d57d3f0ebf78c38894278ac6b9df316bdf5aea...,8569553,1568758389,9/17/2019 10:13:09 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x4b5005baeddf978b1ee157072fd689abeefceef2,26.580702,0.000267,0.057967,207.90,-1
10,0x62bab3abeec4b630cf8b6591b445af52d0e381939102...,8162987,1563295067,7/16/2019 4:37:47 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xd4de58e21f6d9d94ca1d7d424f70a9f59f37b4ac,29.748000,0.000420,0.091287,198.71,-1
11,0x13915733993a7ace5fad3373979916f01f4948acf037...,8163994,1563308995,7/16/2019 8:29:55 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x4828f02c6f8c7e0edd23fa3e66ed75c02d48a56d,29.998000,0.000420,0.091287,198.71,-1
12,0xacd901307b12661e8d2c0a34030b872e6a8af6a7208a...,7138776,1548673330,1/28/2019 11:02:10 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x1c5ebd672e50ad05bbf0a3a707780c0d3f256abb,35.518000,0.000189,0.041079,106.36,-1
13,0x66ba4c6824cc06c8f464e44615f5d022ef0296a206fb...,7260464,1550988634,2/24/2019 6:10:34 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xd8bae043c51974de80b16f02c396d5875ff5aec4,37.788000,0.000231,0.050208,133.42,-1
14,0x3b956f5bace2d5d1c910f5913f7e925295a93dc0ad13...,8129325,1562840199,7/11/2019 10:16:39 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x4828f02c6f8c7e0edd23fa3e66ed75c02d48a56d,39.998000,0.000021,0.004564,268.56,-1
15,0x49fbb6ef0effaf34ed70ae6228cc84b636ad1b9f657e...,8166770,1563345921,7/17/2019 6:45:21 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x4828f02c6f8c7e0edd23fa3e66ed75c02d48a56d,44.998000,0.000231,0.050208,211.29,-1
16,0x2668921f472e11d98fd64c261ba5a05cb2974327762e...,8582245,1568929254,9/19/2019 9:40:54 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x8668449d165178e750d4eb876f05ae738657f685,49.538593,0.000280,0.060751,221.29,-1
17,0xf5e0bf01188522e230254ddb0e5bb35a9e11232be3c8...,8355073,1565871859,8/15/2019 12:24:19 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0xdc32000bff857d4cb2074c9a9d918c35d0241ab8,49.698000,0.000021,0.004564,188.24,-1
18,0x6aba13b5ce3b18917e67678b6150513e6bf4b435a903...,7801733,1558421492,5/21/2019 6:51:32 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x5c1fc8a3cd782ca82ea07e8b143ee4d97efa8282,59.998000,0.000210,0.045644,254.94,-1
19,0xba5ea75e561b27371d307a62b5b5602d3c7afa051d52...,7891450,1559632468,6/4/2019 7:14:28 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x46af827ad650baef832d1c72ae1354677b2f212b,67.348000,0.000042,0.009129,241.10,-1
20,0x2e8f327bf4d4e61b13551c5216da488db4723a669817...,6408154,1538038724,9/27/2018 8:58:44 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x6181726351d59cdfa239c481b06e8c7dd4b6ad79,67.998000,0.000210,0.045644,229.09,-1
21,0x442b115d37f2f0b4899938d41991fbe8923775fe0571...,8400606,1566483660,8/22/2019 2:21:00 PM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x468bc9db45ebc181c33a752926d106be322f8756,69.998000,0.000231,0.050208,190.74,-1
22,0xfbdfa246a31b13a1aed291a5c0e6220effd5102782ea...,6310521,1536646497,9/11/2018 6:14:57 AM,0x491fe5f4724e642c90372b0b95b60c4ac8d13f1c,0x5c1fc8a3cd782ca82ea07e8b143ee4d97efa8282,81.172827,0.000084,0.018257,185.15,-1

## Ethereuem Address 6 
### 0x51C98d91C986204313B0D0E8c35F52bff590896d

In [31]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\6_0x51C98d91C986204313B0D0E8c35F52bff590896d.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0xef947e67741af293edb34479267e261bb3c077195a62...,7085023,1547782088,1/18/2019 3:28:08 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xfdb73a8f85d383fa705259367b45edd33f6703db,4.855000,0.000191,0.041524,120.57
1,0xa7238deca85e58b2ec66220bc8322f97ad7eda11b8ea...,7085577,1547790621,1/18/2019 5:50:21 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xbb9af4f682d9d7db59b5808a63fc097c736c5e1c,0.001120,0.000294,0.063883,120.57
2,0xe72b0e0e747825547f44b46c975736c25399faac4a0b...,7085839,1547794774,1/18/2019 6:59:34 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x7710cca03feb752559759439bcc3a4d93fe67c39,0.030000,0.000147,0.031942,120.57
3,0x5430600875b4ae68f1e11e0a4ea70cf3a8cf21e6baf3...,7086008,1547797207,1/18/2019 7:40:07 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x9bb6e3c3e05c0180f4d348e78b80efde31336744,0.000800,0.000210,0.045631,120.57
4,0x22775019bb2e08d99de7fd161c14bd8d3595dfe5e991...,7086076,1547798418,1/18/2019 8:00:18 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xa44dab707f6f7d129427d330072e9316790be8dd,0.000744,0.000195,0.042437,120.57
...,...,...,...,...,...,...,...,...,...,...
5026,0x9e604db24c2ed65bc1c301007b10a5bf830da7f5b9d4...,8570010,1568764312,9/17/2019 11:51:52 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xd63e4eea66626f16d1747fe887c8250298eeae05,0.518347,0.000336,0.072996,207.90
5027,0xb58428089d7cfebc6637abe0467c73f95da7a7339835...,8571651,1568786356,9/18/2019 5:59:16 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x15db2c869d80d32bc9cfc0dbbbf1bba6fed033e7,0.386300,0.000504,0.109494,210.50
5028,0x2b4e5398b632d15b586e34189bb91046df9f22028cec...,8576930,1568856384,9/19/2019 1:26:24 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xc07a8bd76dd958c9f459e7f3617c7b3b78a04822,0.756733,0.000315,0.068434,221.29
5029,0x1328902d42f0ac1bb0325e96e0d3fdb65cd342ff1935...,8577920,1568870596,9/19/2019 5:23:16 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x8f73d613e2189d65d4271eb56e365919432811f7,0.007583,0.000504,0.109494,221.29
5030,0x6a281066c0322038040489f550e632570d4aac3cd0ff...,8584686,1568962775,9/20/2019 6:59:35 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xafd219e2e190da15b0e10be34563a48709ee7a76,1.000000,0.000504,0.109494,NaN

### Pre-Processing

In [32]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           4.855000     0.000191     0.041524                 120.57
1           0.001120     0.000294     0.063883                 120.57
2           0.030000     0.000147     0.031942                 120.57
3           0.000800     0.000210     0.045631                 120.57
4           0.000744     0.000195     0.042437                 120.57
...              ...          ...          ...                    ...
5025        0.143474     0.000546     0.118618                 207.90
5026        0.518347     0.000336     0.072996                 207.90
5027        0.386300     0.000504     0.109494                 210.50
5028        0.756733     0.000315     0.068434                 221.29
5029        0.007583     0.000504     0.109494                 221.29

[5030 rows x 4 columns]

### Splitting the data

In [33]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
4276        0.000560     0.000147     0.031936                 309.41
555         0.000640     0.000168     0.036505                 134.29
4235        0.000480     0.000126     0.027374                 309.41
568         0.000560     0.000147     0.031942                 134.29
3391        0.000400     0.000105     0.022811                 163.94
...              ...          ...          ...                    ...
4171        1.270000     0.000126     0.027374                 309.41
599         2.144429     0.000126     0.027379                 143.29
1361        0.000560     0.000147     0.031942                 156.45
1547        0.000400     0.000105     0.022815                 158.36
4959        0.285614     0.000105     0.022811                 191.08

[3772 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
4962        0.005000     0.000294     0.063871                 191.08
1929        0.000640     0.000168     0.036498                 158.05
212         0.064000     0.000126     0.027379                 104.50
2244        0.000560     0.000147     0.031936                 158.05
1765        0.000400     0.000105     0.022811                 158.05
...              ...          ...          ...                    ...
2952        0.000560     0.000147     0.031936                 164.39
2414        0.000560     0.000147     0.031936                 156.69
3074        0.000400     0.000105     0.022811                 161.42
25          0.156933     0.000143     0.031029                 118.41
3471        0.000760     0.000199     0.043341                 168.59

[1258 rows x 4 columns]

### Training and testing the model

In [34]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  99.60254372019078 %

<ipython-input-34-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-34-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [35]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x9527cbb8a58a634a6c1212059c68297a90c94e4ec490...,8055397,1561846502,6/29/2019 10:15:02 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x43b2d8f1b2c49d56d5fc76c947770e45ed909c47,0.001920,0.000504,0.109494,317.32,-1
1,0x6bc70195839c19b5c1ca4ff617312d52e05e77874956...,8055405,1561846621,6/29/2019 10:17:01 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xdea7d654e763eb6bb27ee0e875b0006236bc480f,0.001920,0.000504,0.109494,317.32,-1
2,0x9527cbb8a58a634a6c1212059c68297a90c94e4ec490...,8055397,1561846502,6/29/2019 10:15:02 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x43b2d8f1b2c49d56d5fc76c947770e45ed909c47,0.001920,0.000504,0.109494,317.32,-1
3,0x6bc70195839c19b5c1ca4ff617312d52e05e77874956...,8055405,1561846621,6/29/2019 10:17:01 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xdea7d654e763eb6bb27ee0e875b0006236bc480f,0.001920,0.000504,0.109494,317.32,-1
4,0x179b54642c04166eda72da52a90c4c10e7e632b91f5b...,8032459,1561536604,6/26/2019 8:10:04 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xa4118074a5d6e6b4602052cd5bbaf60ff794321c,0.001920,0.000504,0.109494,333.76,-1
5,0x840df0dbe3715c013cb860f0523f8f471e2deb8bd2f6...,7192421,1549619133,2/8/2019 9:45:33 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x9206169e00ff4141adce58ec9ec59d919e193bb0,0.002720,0.000714,0.155145,119.49,-1
6,0x90017f94261f98cd0b8748c51840f008879f41261023...,8535127,1568294250,9/12/2019 1:17:30 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x966879baeffabb27c7ec697ac566ac05c0f93cf1,0.026000,0.000651,0.141430,181.19,-1
7,0xaadf31ecfb1925a36b2ba686d32f80e3c70966db4562...,7223908,1550242136,2/15/2019 2:48:56 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xd187ab1c729164bc1d2b518d98e8ed02925feb17,0.103900,0.000504,0.109514,122.02,-1
8,0x5cfe62ab26c34c47d0b19b0d98c93e4ad823efc9ecb9...,8567862,1568735842,9/17/2019 3:57:22 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xaa3ad26871dcf5a6c6a98bc5fb95670c2f09bfc6,0.140000,0.000546,0.118618,207.90,-1
9,0x8aef9634a8a59aeaa7cebc52d2ee9e437edb25bb289a...,8568022,1568738008,9/17/2019 4:33:28 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xb7e9e670097dceb6491e6342bb0172e6569a8ab6,0.143474,0.000546,0.118618,207.90,-1
10,0x0b2c3eaf15621153e6b0cf9ca4462c2d0eedbf60312d...,8160510,1563261176,7/16/2019 7:12:56 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xa21336d009d715b171d753233e5f2f501d7b55d4,0.593413,0.000504,0.109494,198.71,-1
11,0x2620b431eedcecd026369d048ccef2114f08c13574cb...,7963314,1560603966,6/15/2019 1:06:06 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x80d7a7873be21302c5daf237af89f83c8f2ab012,0.649340,0.000494,0.107321,269.22,-1
12,0xab334d1e1bad854db5d464263374983915cb8108a914...,8066952,1562001389,7/1/2019 5:16:29 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x5c0cd7e41c1d3006b638b197312e855445fe489c,0.952936,0.000504,0.109494,294.17,-1
13,0x15045fede0aef602b2229775c039c50141704cd15239...,8166205,1563338125,7/17/2019 4:35:25 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xb9b9ffafdef3c876e73ce88d441e02276814b0fd,1.788478,0.000504,0.109494,211.29,-1
14,0xacbfd54c216ecd2c6b5fc8e5d687b5029478d8e77da0...,7963195,1560602522,6/15/2019 12:42:02 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x34f83527f380680040a297fef84c2b4be90cdf29,2.019169,0.000504,0.109494,269.22,-1
15,0x4fc0a4b277105369fbb16ae259b2ae8527d602d07d0c...,8159939,1563253030,7/16/2019 4:57:10 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x3843920cb67489be87f1fc4c6bce5c71f3a368b4,2.170000,0.000504,0.109494,198.71,-1
16,0x565e05fc6836d4ac5c527ef3e90b4cc0a4627857d0af...,8166010,1563335429,7/17/2019 3:50:29 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x1ed7bac35bfdf402c47629c35f3d5425266eecdb,2.292500,0.000504,0.109494,211.29,-1
17,0x694a6c3d8a56ca39bbfe97b660616e2899e76f087c93...,8026961,1561463574,6/25/2019 11:52:54 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x61a929bb892ef27283b24c56d5394406fe34d298,2.324960,0.000504,0.109494,316.53,-1
18,0x01d788e7e589608b632ba4c7185f20d3cba01cee04de...,7236162,1550494714,2/18/2019 12:58:34 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x1c0b5fe6e0b1ac019a9273168e213f62c9ae98a8,2.489398,0.000462,0.100350,146.53,-1
19,0x54faf3fb29532e813c19fc801479bae1ab48acfaa797...,8160529,1563261421,7/16/2019 7:17:01 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x919b4b27d7744c179d60e81e2aa7af858db16703,3.809929,0.000504,0.109494,198.71,-1
20,0xb7aaf49e6a3f2ba36c1a561acbc2f40fd0693dd561dc...,7278162,1551346063,2/28/2019 9:27:43 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xe5d628b5ab40ea082f14c453bf109195d11640ef,3.843772,0.000430,0.093543,136.29,-1
21,0x26a6938aa9c323720447c821cb12d2b321e87df63b3d...,8160348,1563258930,7/16/2019 6:35:30 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x919b4b27d7744c179d60e81e2aa7af858db16703,4.106800,0.000504,0.109494,198.71,-1
22,0xc04208d00a34e4b62afecc8afa676e98ec9cb89eef23...,8160177,1563256432,7/16/2019 5:53:52 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x3843920cb67489be87f1fc4c6bce5c71f3a368b4,4.130000,0.000504,0.109494,198.71,-1
23,0x2dfc7bd3f64939f318cb12a070ca59b78bd11a80b602...,8166086,1563336559,7/17/2019 4:09:19 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x1ed7bac35bfdf402c47629c35f3d5425266eecdb,4.444336,0.000504,0.109494,211.29,-1
24,0x95b2305d7f5ba1c8afb0067e54c9fd354dce0da6fbf0...,7277495,1551332190,2/28/2019 5:36:30 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xd24c2486ab48857820ca62fdaeaf71fa8d600e2f,7.293124,0.000364,0.079094,136.29,-1
25,0xa2b737c265f806c2c6edc6d3957b3970f7dc2037b54a...,7963416,1560605235,6/15/2019 1:27:15 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x932743bc99911db0c74302c28300d9e63c6de1a0,10.750000,0.000504,0.109494,269.22,-1
26,0xb181134c9ca649fde9dc2fc52250b1db2506befe6660...,7931707,1560176515,6/10/2019 2:21:55 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x770ee80883e7c875040b7bfacd828b6defd3e0ac,12.490000,0.000504,0.109494,247.96,-1
27,0x3a9cf85448583b5aa708eb9672a923aa05d3df5c0800...,8162525,1563288411,7/16/2019 2:46:51 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x4153c6d37730362cf255267747c0f00bb2a325d0,19.970000,0.000504,0.109494,198.71,-1
28,0x6852c4026acc3ed76ec57a466308f9cb56ac388a641b...,7157881,1549010457,2/1/2019 8:40:57 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x6c40baee0a6909ce375efa04e5f5a9542b1350ca,22.790000,0.000294,0.063883,107.03,-1
29,0x5999955a197ea9b1eeab4e59ef1548d597d709ea70c3...,7810647,1558541887,5/22/2019 4:18:07 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0xe716db5bdf85e6d48737157813a7aa421da17fb5,28.130000,0.000294,0.063871,243.46,-1
30,0x5d6fe97dea171224a435f4044cf6733350218d8e27de...,7154349,1548948622,1/31/2019 3:30:22 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x7d68259aa498cd6937577d56579654ea7c48b952,66.991950,0.000189,0.041068,106.89,-1
31,0x496c6a6648f4b5050c31ed1dbf42e5a91bc85315af7f...,7778604,1558107803,5/17/2019 3:43:23 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x4bb2992f4d3123efe8ff8ad3ee49f876edbe9c5d,73.440000,0.000336,0.072996,244.84,-1
32,0x51e1a42a8211c5222334e4097f0ad8a17097b8f5eb1d...,8025895,1561449287,6/25/2019 7:54:47 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x2c9fab0e7891fb5670741348a3e6e32f53d2ab56,75.120000,0.000504,0.109494,316.53,-1
33,0x35a20bf57cbfaa7bf21f36b5f391f3af1c3e7c67364e...,7470913,1553965180,3/30/2019 4:59:40 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x6e660233facfb4b8168e6228fd28de7c0823eeb7,199.990000,0.000126,0.027379,143.29,-1
34,0x09740d4c086c653f6edc6e67fb811a94e03f72cc137a...,7951151,1560440114,6/13/2019 3:35:14 PM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x2c9fab0e7891fb5670741348a3e6e32f53d2ab56,204.990000,0.000107,0.023267,255.09,-1
35,0x52317dd940dcf3bc6b9c2bebf84221f97123f5bded78...,8026458,1561456784,6/25/2019 9:59:44 AM,0x51c98d91c986204313b0d0e8c35f52bff590896d,0x2c9fab0e7891fb5670741348a3e6e32f53d2ab56,339.170000,0.000504,0.109494,316.53,-1

## Ethereuem Address 7
### 0x337D61EDe4587cd2ad747E1afB13c31AA08E6903

In [36]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\7_0x337D61EDe4587cd2ad747E1afB13c31AA08E6903.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x4f014121a8673cbd27d62a4adc81c2372c4ee9e518b0...,7164913,1549135482,2/2/2019 7:24:42 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xcbe7dedc0342abe01b32f4d8143c06b155079f8e,0.06070,0.000147,0.031971,111.00
1,0xc4ff011e8ad171542d5769189e01eec9cb6f46c040ad...,7165143,1549139211,2/2/2019 8:26:51 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xcbe7dedc0342abe01b32f4d8143c06b155079f8e,0.13194,0.000147,0.031971,111.00
2,0x6e58abd28bb52332bc878704f40d30a49b298c0c6fc9...,7167421,1549178380,2/3/2019 7:19:40 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xf352e754baa709cab17bfe60759949e549f18ded,0.03600,0.000147,0.031971,107.21
3,0x3cadfd36539993f2031ae873bb80ef43d2ceeb1ce236...,7168780,1549203464,2/3/2019 2:17:44 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x35c2b5c2a420d1e9d0529c88587a782aaf7b3822,0.03600,0.000147,0.031971,107.21
4,0x3f7b2bf04842a2d9aff8f25d4acea0f1e8e91c8c7b2c...,7169503,1549216862,2/3/2019 6:01:02 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x35c2b5c2a420d1e9d0529c88587a782aaf7b3822,0.01000,0.000147,0.031971,107.21
...,...,...,...,...,...,...,...,...,...,...
2170,0x61e0b8f9e8493587b9aaf38e9aeb0319a10a3834449d...,8583070,1568940926,9/20/2019 12:55:26 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xe85a73da025b80b40dd6f5eb4dec6d8e42ed2c60,0.80183,0.000441,0.095913,NaN
2171,0x53acd67efe4195954a03cf195fb0bcece25e5666382b...,8583780,1568950039,9/20/2019 3:27:19 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xede64caba3cb09be2a58b5d9aafe58e47154959e,0.51840,0.000609,0.132451,NaN
2172,0xf8f6b1a5d58eac9163ed33447a3862b1f126214374e3...,8583832,1568950879,9/20/2019 3:41:19 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x25b5f62f3f108b3087e0294129602e264f218672,0.06830,0.000609,0.132451,NaN
2173,0x35c8ddc5d7f95ea835fb82be8df7ea2d0625a24e3953...,8584200,1568956145,9/20/2019 5:09:05 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xd9b2316cff9995be114d348e23e698696e1dbcbb,0.44390,0.000609,0.132451,NaN
2174,0x6cfe0ea1359944c27a9327500c751af8059ee03bf34f...,8585380,1568972221,9/20/2019 9:37:01 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x3a69cc7d6c0715dc362f7b0d4a35d203a2be5ae2,0.19011,0.000630,0.137019,NaN

### Pre-Processing

In [37]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0            0.06070     0.000147     0.031971                 111.00
1            0.13194     0.000147     0.031971                 111.00
2            0.03600     0.000147     0.031971                 107.21
3            0.03600     0.000147     0.031971                 107.21
4            0.01000     0.000147     0.031971                 107.21
...              ...          ...          ...                    ...
2165         0.09070     0.000630     0.137019                 221.29
2166         0.09070     0.000630     0.137019                 221.29
2167         0.08810     0.000630     0.137019                 221.29
2168         1.04800     0.000630     0.137019                 221.29
2169         1.29630     0.000588     0.127884                 221.29

[2170 rows x 4 columns]

### Splitting the data

In [38]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
92           0.05000     0.000336     0.073077                 146.53
1809         0.01457     0.000105     0.022836                 188.46
720          1.09870     0.000325     0.070684                 267.42
146          0.00400     0.000231     0.050240                 149.23
1948         0.01020     0.000147     0.031971                 179.13
...              ...          ...          ...                    ...
599          0.05440     0.000126     0.027404                 163.61
1599         0.01457     0.000063     0.013702                 185.69
1361         0.05059     0.000105     0.022836                 225.99
1547         0.00800     0.000105     0.022836                 188.24
863          0.00230     0.000210     0.045673                 264.51

[1627 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1416         2.16880     0.000063     0.013702                 210.47
2020         0.10960     0.000168     0.036538                 169.47
1685         0.00940     0.000084     0.018269                 202.43
19           0.02900     0.000126     0.027404                 120.76
584          0.00030     0.000147     0.031971                 161.42
...              ...          ...          ...                    ...
1931         0.01000     0.000210     0.045673                 178.76
1125         0.19200     0.000420     0.091346                 198.71
429          0.03220     0.000168     0.036538                 140.23
1123         0.03581     0.000504     0.109615                 198.71
1419         0.02078     0.000063     0.013702                 210.47

[543 rows x 4 columns]

### Training and testing the model

In [39]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  98.89502762430939 %

<ipython-input-39-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-39-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [40]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x7381099995bb21794969742ca4ad893ea7b4feaace08...,8579901,1568897386,9/19/2019 12:49:46 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x259672d9fc8f87f253456502ebb1afef3b8616a1,0.08800,0.000630,0.137019,221.29,-1
1,0x5a1196727b13cbd0f53fd3a33677e856662d9c1bdb40...,8580900,1568910911,9/19/2019 4:35:11 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x67206195ec7e527b64f3469ba8c698dfb0a2c78a,0.08810,0.000630,0.137019,221.29,-1
2,0xcf987c5345ece632270b03c435ea3bebe95028a6e5d1...,8580731,1568908628,9/19/2019 3:57:08 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x1759c32e1d8bbf2c3a3082e3a2a19867120b7369,0.09070,0.000630,0.137019,221.29,-1
3,0x556ae701af54b2913e799857f2e4abb55ae662a9a89e...,8580763,1568908990,9/19/2019 4:03:10 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xcbe86a5a5a2109304341133539b305a2470cd41f,0.09070,0.000630,0.137019,221.29,-1
4,0xcf987c5345ece632270b03c435ea3bebe95028a6e5d1...,8580731,1568908628,9/19/2019 3:57:08 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x1759c32e1d8bbf2c3a3082e3a2a19867120b7369,0.09070,0.000630,0.137019,221.29,-1
5,0x556ae701af54b2913e799857f2e4abb55ae662a9a89e...,8580763,1568908990,9/19/2019 4:03:10 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xcbe86a5a5a2109304341133539b305a2470cd41f,0.09070,0.000630,0.137019,221.29,-1
6,0x19e334fa36f8f682123965e7a655d9b147509b34a916...,8573048,1568804582,9/18/2019 11:03:02 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x598ad82257a9bfb2b3a0e9a6594aaf427c49f002,0.40389,0.000630,0.137019,210.50,-1
7,0xada3a553e9017c359c8dc58f5b55778f2863c42848ee...,8573158,1568806180,9/18/2019 11:29:40 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x47f17faf6847cb19bb484d97e58ba0b1c98397b9,0.40673,0.000630,0.137019,210.50,-1
8,0xfc60451c2c691e13487bd0e4888ed052da63d993634b...,8580707,1568908259,9/19/2019 3:50:59 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xa569a37d07bd689320721bb240179aa83cfef8c8,0.99988,0.000630,0.137019,221.29,-1
9,0x54219b92bc987543c07e9d12a987817bf6de17da240e...,8581026,1568912687,9/19/2019 5:04:47 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xfe78a34854677e983006f540abb5b73777cde5de,1.04800,0.000630,0.137019,221.29,-1
10,0x3a7f20e255229e0c5e73413739c5c605ba9e17f7bfb6...,8580053,1568899409,9/19/2019 1:23:29 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x838b4851573784411efebc9e5c1eb05661c92832,1.22800,0.000630,0.137019,221.29,-1
11,0x9e60ae801f12ea38fc60179801a660c463e5849cb6d7...,8568108,1568739395,9/17/2019 4:56:35 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x96cfbe45ac42fa1e6335c6e88db45333847af4a8,2.64400,0.000630,0.137019,207.90,-1
12,0x8b5def73f8d21c1cdb140132b70eba8b57901075dfc5...,8528130,1568200106,9/11/2019 11:08:26 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x9a69126a6b740c26f88b15d30ebec294a80046e9,9.99200,0.000420,0.091346,178.48,-1
13,0x83a91f7448bd43435cfacbfc770085d20fb06190ed1f...,8540439,1568365918,9/13/2019 9:11:58 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xd58e0a05fe62fff9883f3cb6ca961e3d8dbac95e,10.26734,0.000462,0.100480,181.56,-1
14,0xca9954a3495d459197e109eb45af5fc49a6772fd6120...,8009022,1561221257,6/22/2019 4:34:17 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x00d199691976d248e17b8e8afcd05f8232154207,14.69890,0.000231,0.050240,309.41,-1
15,0x8d5a0f2350d4fe75191b0957f7eb3879826fd7997357...,8560913,1568642279,9/16/2019 1:57:59 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x9a69126a6b740c26f88b15d30ebec294a80046e9,14.99080,0.000483,0.105048,197.85,-1
16,0x13ece0a4f936c4aa186bb7299ec65dfeffd4d88cff79...,7855164,1559141747,5/29/2019 2:55:47 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x90c30e3759c1240f5295730668809fee4ab3e1d9,16.48959,0.000378,0.082211,269.60,-1
17,0xc2d1a8b8ff26e7d2f7a13f09c3eb34762d6ac0a77d23...,8056176,1561856900,6/30/2019 1:08:20 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x00d199691976d248e17b8e8afcd05f8232154207,16.67963,0.000420,0.091346,290.15,-1
18,0x97a912fdd794baa592fda0694b74a098a9ed0d3a2dda...,7893098,1559654510,6/4/2019 1:21:50 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xad60343f891dd7bf89ce354ee139cabc70a5d53c,17.89870,0.000273,0.059375,241.10,-1
19,0x23e7d9dc8b1fa016b459e3984905196c48d6207efd0c...,7849756,1559069731,5/28/2019 6:55:31 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x888820a1e6c47fe07ad9a9f13b03814e9cc2ba4b,19.99940,0.000126,0.027404,271.45,-1
20,0xb9466e3b699cddaddd1baf8b6a2211150928dbb156b3...,8121307,1562732606,7/10/2019 4:23:26 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xa340ed29876b463682c2d112d1a214afdf52db79,20.00000,0.000169,0.036767,288.64,-1
21,0x4f9f7a82ff66f784fad5f8a1114c4ec5e708017c184f...,8509151,1567944003,9/8/2019 12:00:03 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0x9a69126a6b740c26f88b15d30ebec294a80046e9,24.00240,0.000399,0.086779,181.67,-1
22,0x1866c4d3fa67f1d37277ffa09614793279d2a9a2da1c...,8129851,1562847073,7/11/2019 12:11:13 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xa340ed29876b463682c2d112d1a214afdf52db79,30.00000,0.000185,0.040192,268.56,-1
23,0x0edb94da22ca2c22d7d5df5aad834686f7c251cf2d72...,8078450,1562157047,7/3/2019 12:30:47 PM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xa340ed29876b463682c2d112d1a214afdf52db79,30.00000,0.000210,0.045673,302.17,-1
24,0x9fa9250d09ddf9c401dba8abaa19b9f62b0f978e593f...,8385217,1566276937,8/20/2019 4:55:37 AM,0x337d61ede4587cd2ad747e1afb13c31aa08e6903,0xe4ef4c31d4a6f5b14c036d2ee458773d64508711,32.10600,0.000210,0.045673,196.55,-1

## Ethereuem Address 8
### 0x261d363D235E2a91B7E208c244163148277aB9Cf

In [41]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\8_0x261d363D235E2a91B7E208c244163148277aB9Cf.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x9452e0ef765b289c0a4854adb121533fd927b8687b2f...,5015764,1517553079,2/2/2018 6:31:19 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x57904bb1ad06e48e159bcfa98a7089fa7eab8bd4,2.045577,0.000840,0.182624,917.47
1,0x82659eb9ce2b715865fbab4d453563c906fb13fd9d78...,5398075,1523117108,4/7/2018 4:05:08 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x496494249f625c905904f1a76d23fefa5414b887,0.040000,0.000840,0.182624,384.98
2,0x529caa347a548e13f41bdb1f08b4c2174d523fa10a67...,5446477,1523817229,4/15/2018 6:33:49 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x7ae17a0f6f8f02b5b6e76b327db15f91306194e6,100.000000,0.000840,0.182624,534.15
3,0xc246e73602c715870a8a163ed97c0e03415013f9cc89...,5457211,1523974862,4/17/2018 2:21:02 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xa574c931f8fb548806b6e4fb059d9640453e3ac5,0.109000,0.000840,0.182624,503.03
4,0xaa6fbae4ab847c8a6ac621bf662cc9e2173860f76e4a...,5457480,1523978910,4/17/2018 3:28:30 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x59423943f6c2e69d2b308085f7af08538a7042f9,0.005000,0.000840,0.182624,503.03
...,...,...,...,...,...,...,...,...,...,...
2319,0xc2157b8c250de7b77bebcb9f8da53582a927403346d3...,8580463,1568905066,9/19/2019 2:57:46 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xddbeefac9c527927b3579e71d78f74cc190fbf2e,0.055000,0.000462,0.100416,221.29
2320,0xe332a88120a4132e11c9889bb70c43b3a234226825e9...,8580497,1568905517,9/19/2019 3:05:17 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xedeed5dc7a77437e3d832d40dc33eff14fb7d9a6,0.100000,0.000466,0.101329,221.29
2321,0x59fd32bdc28739b562824983eead45d195058e44ac52...,8581043,1568912963,9/19/2019 5:09:23 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xedeed5dc7a77437e3d832d40dc33eff14fb7d9a6,0.100000,0.000525,0.114109,221.29
2322,0xa6923d635ee51f4285decacda93a98f48b3ae8989cce...,8585265,1568970738,9/20/2019 9:12:18 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x41eefc003ae50b6d271abe278c130d2a7f003eaf,0.012300,0.000525,0.114109,NaN
2323,0x8f90f34092662c2eaac5afd2f9f1899cda7770256eec...,8585286,1568971014,9/20/2019 9:16:54 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x528ddd11f8fe187b78aea204fc6db1a466edc6fd,0.600000,0.000630,0.136931,NaN

### Pre-Processing

In [42]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           2.045577     0.000840     0.182624                 917.47
1           0.040000     0.000840     0.182624                 384.98
2         100.000000     0.000840     0.182624                 534.15
3           0.109000     0.000840     0.182624                 503.03
4           0.005000     0.000840     0.182624                 503.03
...              ...          ...          ...                    ...
2317        0.500000     0.000525     0.114109                 221.29
2318        0.100000     0.000546     0.118673                 221.29
2319        0.055000     0.000462     0.100416                 221.29
2320        0.100000     0.000466     0.101329                 221.29
2321        0.100000     0.000525     0.114109                 221.29

[2322 rows x 4 columns]

### Splitting the data

In [43]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1150        0.130000      0.00021     0.045644                 254.94
1614        0.052000      0.00042     0.091287                 221.28
1343        0.150000      0.00021     0.045644                 231.43
1515        0.550000      0.00021     0.045644                 309.37
1981        1.000000      0.00021     0.045644                 188.46
...              ...          ...          ...                    ...
599        10.000000      0.00021     0.045656                 120.57
1599        0.190000      0.00021     0.045644                 226.09
1361        0.100000      0.00021     0.045644                 263.76
1547        0.050000      0.00021     0.045644                 307.89
863         0.207609      0.00021     0.045656                 166.28

[1741 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
882            0.100     0.000210     0.045656                 175.57
489            0.930     0.000420     0.091312                 202.79
2182           0.018     0.000336     0.073030                 180.84
1798           0.010     0.000210     0.045644                 208.62
1209           0.025     0.000378     0.082158                 269.60
...              ...          ...          ...                    ...
407            0.014     0.000210     0.045656                 221.63
1917           2.000     0.000210     0.045644                 187.32
853            0.020     0.000210     0.045656                 166.28
1820           0.500     0.000210     0.045644                 186.49
1998           0.080     0.000210     0.045644                 173.01

[581 rows x 4 columns]

### Training and testing the model

In [44]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

<ipython-input-44-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)

The Accuracy of the following anamoly detection unit is  98.9672977624785 %

<ipython-input-44-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [45]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x33b7d992bc8307fd4eb7a9d33d24d78cf69a8520a174...,6110532,1533732407,8/8/2018 12:46:47 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xc823a110ebb5b5e0a8a6856de4d7e8e8d71e0e6f,0.033000,0.001281,0.278502,355.57,-1
1,0x3a0d6beaafde7135625b89866d24cd2599b0a3b857b5...,8545945,1568440715,9/14/2019 5:58:35 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x4fbd071b26bc038ced9de7b021a3554c84525fcf,0.036000,0.001071,0.232782,188.90,-1
2,0xcc2d6e755055c1b995a6d1bf84fe24d4d1044d040c98...,6111042,1533739999,8/8/2018 2:53:19 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xf885da1a1ff0c38272d80b39eb4251a1f0409451,0.052000,0.001281,0.278502,355.57,-1
3,0x5ab4985e1473a6828b4c8f339b60b83564a269299fdb...,5885239,1530429668,7/1/2018 7:21:08 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x3ee7f666fd204023953288e91455a2c2d12cfe64,0.092000,0.001344,0.292199,451.95,-1
4,0x80e47ff7a69d3b4f87bd61019751263e0fb14b73d2de...,5594049,1526027363,5/11/2018 8:29:23 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x429ae41c74e35fff3f1ef0d60a538d8c350c303d,0.100000,0.001050,0.228280,677.80,-1
5,0x43eacc12b74c0417fd5b8fe672f04c4a7b1e92f34100...,5477841,1524282226,4/21/2018 3:43:46 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.150000,0.000840,0.182624,605.17,-1
6,0xdd8a4d0574606928ac4b4ba0e1ff2234705cc72843b4...,6232254,1535509965,8/29/2018 2:32:45 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xee00c2e8dae040b0186b30a179d4013dbfb2f326,0.150000,0.001155,0.251109,288.67,-1
7,0x13a65c323ffd46969550c9d641b6bfeac66b8f6adc47...,6232330,1535511111,8/29/2018 2:51:51 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xda4b075fcaf9d19ce76b81603372353c891855e5,0.150000,0.001155,0.251109,288.67,-1
8,0xdd8a4d0574606928ac4b4ba0e1ff2234705cc72843b4...,6232254,1535509965,8/29/2018 2:32:45 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xee00c2e8dae040b0186b30a179d4013dbfb2f326,0.150000,0.001155,0.251109,288.67,-1
9,0x13a65c323ffd46969550c9d641b6bfeac66b8f6adc47...,6232330,1535511111,8/29/2018 2:51:51 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xda4b075fcaf9d19ce76b81603372353c891855e5,0.150000,0.001155,0.251109,288.67,-1
10,0x045cca75a6c97b9f7774ee5ef8cc882587bfe7145758...,6111524,1533746912,8/8/2018 4:48:32 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xfb5304ac71340315a390424cc8bd9d6dfe7e5e8f,0.214124,0.001281,0.278502,355.57,-1
11,0xaffff3268c63f4bdf81fb0d8d3edbb5e5d81ac44e15a...,5474266,1524229712,4/20/2018 1:08:32 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.300000,0.000840,0.182624,617.16,-1
12,0x7ae558f9724d9eb8734ba8b4c13079486b35b1644d7d...,8541812,1568384304,9/13/2019 2:18:24 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x01001e2ce95ec2ed64b591a4c53e90745c605fa3,0.300000,0.000882,0.191703,181.56,-1
13,0xfe36de1f43b4e9ea336caa4115cd582749c26bb0a232...,5474325,1524230679,4/20/2018 1:24:39 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.350000,0.000840,0.182624,617.16,-1
14,0x6b8e5beebd2c1287ade98097005e4c6e3ae07f677464...,5474450,1524232420,4/20/2018 1:53:40 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.350000,0.000840,0.182624,617.16,-1
15,0xfe36de1f43b4e9ea336caa4115cd582749c26bb0a232...,5474325,1524230679,4/20/2018 1:24:39 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.350000,0.000840,0.182624,617.16,-1
16,0x6b8e5beebd2c1287ade98097005e4c6e3ae07f677464...,5474450,1524232420,4/20/2018 1:53:40 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.350000,0.000840,0.182624,617.16,-1
17,0xeb1b1552d85e6351a22ff0ce8c6dae2fd1787867ab79...,6768502,1543126708,11/25/2018 6:18:28 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xe4422643ee018f6b6d9ff2466b8250f1dd454e99,0.359000,0.000966,0.210018,116.75,-1
18,0x543a5cb884aded712dc969749549ab0bbf6b9f2fa0cb...,5474533,1524233516,4/20/2018 2:11:56 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
19,0x7bb4e056ede4c0d4291be488e60160acaa8954c473d7...,5474615,1524234601,4/20/2018 2:30:01 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
20,0x1e0dc074bd15e4db848b55cc39cba41910d506d0d83c...,5474665,1524235374,4/20/2018 2:42:54 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
21,0x543a5cb884aded712dc969749549ab0bbf6b9f2fa0cb...,5474533,1524233516,4/20/2018 2:11:56 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
22,0x7bb4e056ede4c0d4291be488e60160acaa8954c473d7...,5474615,1524234601,4/20/2018 2:30:01 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
23,0x1e0dc074bd15e4db848b55cc39cba41910d506d0d83c...,5474665,1524235374,4/20/2018 2:42:54 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
24,0x543a5cb884aded712dc969749549ab0bbf6b9f2fa0cb...,5474533,1524233516,4/20/2018 2:11:56 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
25,0x7bb4e056ede4c0d4291be488e60160acaa8954c473d7...,5474615,1524234601,4/20/2018 2:30:01 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
26,0x1e0dc074bd15e4db848b55cc39cba41910d506d0d83c...,5474665,1524235374,4/20/2018 2:42:54 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x51acf809023ef8fe3e2bac78fbbb87be84e09692,0.500000,0.000840,0.182624,617.16,-1
27,0x888b83398497a571b894947fbacad710b39504d01686...,5461613,1524040339,4/18/2018 8:32:19 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x93d69adecba1e3cc0285fd19d9be7b2d9a40d145,0.800000,0.000840,0.182624,525.78,-1
28,0x46886091a5b98a4e6eaab068e1747dca1d83aaeb5b44...,6108729,1533706566,8/8/2018 5:36:06 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x988a5ba182d557309061615a638502471bd969b7,1.000000,0.001281,0.278502,355.57,-1
29,0x30398a1b0153c1292175b694457384332afdce825aea...,6143767,1534218637,8/14/2018 3:50:37 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x9a9e116dc0dac1c5d339cbb5fbf6f88a6e1b190e,1.450000,0.001155,0.251109,278.31,-1
30,0xc56f599b3b18f26fa9dc9741152de658ff534582ff1c...,6113589,1533777219,8/9/2018 1:13:39 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xb737861f831cb9e0fe8ce849f0473131f530337e,2.000000,0.000924,0.200887,363.51,-1
31,0x9452e0ef765b289c0a4854adb121533fd927b8687b2f...,5015764,1517553079,2/2/2018 6:31:19 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x57904bb1ad06e48e159bcfa98a7089fa7eab8bd4,2.045577,0.000840,0.182624,917.47,-1
32,0x54734a3e5eea13f79734bc6c94aa3d92b1424aadb45a...,5466481,1524111895,4/19/2018 4:24:55 AM,0x261d363d235e2a91b7e208c244163148277ab9cf,0xaedf7aa9d55a6fbbe72cc4c013cbc554b1881194,2.250000,0.000840,0.182624,567.25,-1
33,0x529caa347a548e13f41bdb1f08b4c2174d523fa10a67...,5446477,1523817229,4/15/2018 6:33:49 PM,0x261d363d235e2a91b7e208c244163148277ab9cf,0x7ae17a0f6f8f02b5b6e76b327db15f91306194e6,100.000000,0.000840,0.182624,534.15,-1

## Ethereuem Address 9
### 0xFa453aec042a837e4AEBbADAB9d4E25B15FAd69D

In [46]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\9_0xFa453aec042a837e4AEBbADAB9d4E25B15FAd69D.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x9d409af83740d82db859176c49e6442258363ddf34c7...,6737729,1542691074,11/20/2018 5:17:54 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x72296cde04c7b6184c2bc40ee9042c5a094821a7,9.800,0.000126,0.027449,130.74
1,0xf2f161e92d6014540f070003abb1b9daa550d249f5c6...,6739382,1542715060,11/20/2018 11:57:40 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x0c7719f1d7ed41271cbba92ec153afa6610228f8,0.001,0.000210,0.045637,130.74
2,0xf948e2ece1c414ec14ea2b25fdd2afacc129ba68388c...,6834725,1544072721,12/6/2018 5:05:21 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0xf1ce3eda082bf9bc69feadd04216d9c9e52cac71,300.000,0.000128,0.027839,90.43
3,0xe63682e80dbecd84faef34ff9f4b880a3c6663fadc85...,6841008,1544162745,12/7/2018 6:05:45 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x0c7719f1d7ed41271cbba92ec153afa6610228f8,0.001,0.000107,0.023275,93.61
4,0x4ce96429c0c8fa7bafd19cde8663cf939e00fc7a7a6e...,6848573,1544271634,12/8/2018 12:20:34 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0xf1ce3eda082bf9bc69feadd04216d9c9e52cac71,670.000,0.000084,0.018255,91.44
...,...,...,...,...,...,...,...,...,...,...
2086,0x8557bc346da0d422a6d6097cf069b2746ddbab1792bd...,8581881,1568924492,9/19/2019 8:21:32 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x94e509b0f855297c0b99ab61bff027e0ad114121,513.000,0.001050,0.228186,221.29
2087,0x862c1e76f88bb97ed83869bcbecdf62e5634d9d37836...,8581881,1568924492,9/19/2019 8:21:32 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x94e509b0f855297c0b99ab61bff027e0ad114121,653.000,0.001050,0.228186,221.29
2088,0x539e9d72db9b77453a9021425919ee20e3419f6a3bfa...,8583053,1568940704,9/20/2019 12:51:44 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x94e509b0f855297c0b99ab61bff027e0ad114121,1732.000,0.001050,0.228186,NaN
2089,0x0dc511202030bff48a8c083fec080e45476c3a85b235...,8583576,1568947387,9/20/2019 2:43:07 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x366064cc2baa69ff0bb0dd7dd07cb266e5105759,6000.000,0.001050,0.228186,NaN
2090,0x28aad84c5eb43b2dc9fe8243c5f2c42215ad707dae6d...,8583710,1568949255,9/20/2019 3:14:15 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0xfb067f72cccd77e7342b5772de1f3ad1c29e121d,762.000,0.001050,0.228186,NaN

### Pre-Processing

In [47]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0              9.800     0.000126     0.027449                 130.74
1              0.001     0.000210     0.045637                 130.74
2            300.000     0.000128     0.027839                  90.43
3              0.001     0.000107     0.023275                  93.61
4            670.000     0.000084     0.018255                  91.44
...              ...          ...          ...                    ...
2083         233.000     0.001050     0.228186                 221.29
2084        1164.000     0.001050     0.228186                 221.29
2085         465.000     0.001050     0.228186                 221.29
2086         513.000     0.001050     0.228186                 221.29
2087         653.000     0.001050     0.228186                 221.29

[2088 rows x 4 columns]

### Splitting the data

In [48]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
1904           0.001     0.001050     0.228186                 178.76
1563           0.001     0.001050     0.228186                 219.41
195            0.001     0.000063     0.013691                 170.66
1209           0.001     0.000781     0.169770                 268.94
1294           0.001     0.000252     0.054765                 268.94
...              ...          ...          ...                    ...
599          949.000     0.000983     0.213582                 309.41
1599           0.001     0.000252     0.054765                 219.23
1361           0.001     0.000252     0.054765                 226.16
1547           0.001     0.001050     0.228186                 216.66
863            0.001     0.001050     0.228186                 268.56

[1566 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
216         1000.000     0.000021     0.004564                 156.69
418            9.601     0.000021     0.004564                 271.45
2071           0.001     0.001050     0.228186                 221.29
1178           0.001     0.000378     0.082147                 268.94
1735         490.000     0.000849     0.184584                 210.47
...              ...          ...          ...                    ...
938            0.001     0.001050     0.228186                 268.56
974            0.001     0.000756     0.164294                 275.41
1138           0.001     0.000756     0.164294                 268.94
792            0.001     0.000756     0.164294                 268.56
1630        1414.000     0.000252     0.054765                 209.82

[522 rows x 4 columns]

### Training and testing the model

In [49]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

The Accuracy of the following anamoly detection unit is  99.23371647509579 %

<ipython-input-49-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-49-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

### Transactions which has been marked as anamoly

In [50]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0x31ea03be59dca3cdc626411e04a91f3edb2f185726e4...,8264767,1564661977,8/1/2019 12:19:37 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,200.0,0.001685,0.366239,217.51,-1
1,0xa4194da05156bf2735ad22c8700ec792825760dd9f72...,8115403,1562653288,7/9/2019 6:21:28 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,498.0,0.001685,0.366239,307.89,-1
2,0x01bf3314e23db153059e7206cff2213af91d6a351aca...,7994394,1561024681,6/20/2019 9:58:01 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,510.0,0.001685,0.366239,272.21,-1
3,0x0f2789f54bfe94326baa061f380288107f8803897cb5...,7975130,1560763685,6/17/2019 9:28:05 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,727.0,0.001685,0.366239,273.92,-1
4,0x2332d2c21ce40cdeeea177d9ac7387f5709f9954e070...,8001183,1561116207,6/21/2019 11:23:27 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,845.0,0.001685,0.366239,296.03,-1
5,0x60deffaea7df317037bc86451609c7385e07723c408e...,8378595,1566187705,8/19/2019 4:08:25 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,900.0,0.001685,0.366239,202.43,-1
6,0x97bdb76658ccc444495eb05d7a8dbd14240c90c35894...,8039173,1561627688,6/27/2019 9:28:08 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,953.0,0.001685,0.366239,294.07,-1
7,0x22ba46daad58a3a40367619775ea0953cf0af2463921...,8353524,1565850805,8/15/2019 6:33:25 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,1000.0,0.001685,0.366239,188.24,-1
8,0xb9fbc64a873130d63433f8297d578bf5ae72f4028a2c...,7975674,1560771108,6/17/2019 11:31:48 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,1094.0,0.001685,0.366239,273.92,-1
9,0xc7c44d7b704d1278c4a8306acf712aee1c1399e66a27...,7991603,1560986473,6/19/2019 11:21:13 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,1726.0,0.001685,0.366239,269.01,-1
10,0x07da1012ca26eee783d36b494860d32e784b361849fe...,8035193,1561573641,6/26/2019 6:27:21 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x4c8a42bf55d88749b9ea22e12df1a2a17d16303e,3840.0,0.001050,0.228186,333.76,-1
11,0x99a9e0783b70fee2ad6a634ef84d9f6f65d0f4f83548...,8113654,1562629711,7/8/2019 11:48:31 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9a5b7bfd17857f1148292b61e092296255db84c0,4709.0,0.000404,0.087897,313.34,-1
12,0x13caf1f94304ec7f172fc34513e00ffb00e918f9d165...,6972731,1546069641,12/29/2018 7:47:21 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9f9643c8b413b32c3a1270068487f341e5be8bfd,5000.0,0.000168,0.036598,137.30,-1
13,0x734a5ef5414bcf95785a63067655b8b5530622bbffd0...,8399485,1566468265,8/22/2019 10:04:25 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x34f060f2c3d3a56011a46d817cc06e150b392d8a,5076.0,0.000756,0.164294,190.74,-1
14,0xae0b8a694564339c42bb940b0c30b608d4150fbb4662...,7990814,1560975269,6/19/2019 8:14:29 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0xe0fc1f42320dcf40a837346e921596bc44d5a749,5135.0,0.000756,0.164294,269.01,-1
15,0xf7d783e9d82b7a2b025b9372ad6fe352ba621f2e1f8b...,8514672,1568018426,9/9/2019 8:40:26 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x34f060f2c3d3a56011a46d817cc06e150b392d8a,5805.0,0.001050,0.228186,180.84,-1
16,0x713b303f8b6c7e2d33ba568890d3a09d3fa9fa260671...,8515038,1568023630,9/9/2019 10:07:10 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x34f060f2c3d3a56011a46d817cc06e150b392d8a,6591.0,0.001050,0.228186,180.84,-1
17,0xc7fbf8664d956abb733b7e427bb4f89a8b1a46e30c73...,8355841,1565882292,8/15/2019 3:18:12 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x4b3eea6522d87324b68e4fcff6762ca98de71eb5,7500.0,0.000756,0.164294,188.24,-1
18,0xb924fc9d00d5c9af79ad34975ba11ec58de3c9b443e5...,8104071,1562500841,7/7/2019 12:00:41 PM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x4c8a42bf55d88749b9ea22e12df1a2a17d16303e,7777.0,0.000252,0.054765,306.43,-1
19,0x0a42a4dc987f0429a0c3be884e80f25a0c692b825b53...,7202244,1549796203,2/10/2019 10:56:43 AM,0xfa453aec042a837e4aebbadab9d4e25b15fad69d,0x9f9643c8b413b32c3a1270068487f341e5be8bfd,10000.0,0.000084,0.018299,125.58,-1

## Ethereuem Address 10
### 0xFC04F920C7195B75FBb3b387C9A3dbFA8d10F651

In [51]:
dfs = pd.read_csv(r"D:\Desktop\nitk\6th_SEM\ML_Project\transaction_data\10_0xFC04F920C7195B75FBb3b387C9A3dbFA8d10F651.csv")
dfs1=dfs
display(dfs)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth
0,0x7ce58942634630bfb37801b36a085dd025cd0f5910dc...,5529503,1525051781,4/30/2018 1:29:41 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.370434,0.000164,0.035679,670.04
1,0x98009e7679d86d9acc87f033e7b6a43ed9a40b14b126...,5530798,1525071348,4/30/2018 6:55:48 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.994791,0.000204,0.044242,670.04
2,0x929b2d61ce5828342a4b4367e59458372d918c1463d6...,5531268,1525078651,4/30/2018 8:57:31 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.159414,0.000204,0.044242,670.04
3,0x841874c74fc0f9af7055ef6ec7596a724186e8709832...,5531453,1525081545,4/30/2018 9:45:45 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.100858,0.000328,0.071358,670.04
4,0x4bc4db6600c23a49f6a623b8817e9b13a984b722e0bd...,5532083,1525090852,4/30/2018 12:20:52 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.586255,0.000230,0.049950,670.04
...,...,...,...,...,...,...,...,...,...,...
2861,0xae4c1e0aa2c25a1edd233e31000b6b0556ddd58e2e94...,8496129,1567769476,9/6/2019 11:31:16 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,17.585908,0.000713,0.154833,169.47
2862,0x441b057a1c9a7f08ebd211e8f7dcc12f0d07ccf1a26c...,8496577,1567775118,9/6/2019 1:05:18 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,14.273986,0.000784,0.170316,169.47
2863,0xb9d3aaaceac5af50bab97a21750530554d6a02bc5195...,8507937,1567927544,9/8/2019 7:25:44 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,17.999538,0.000499,0.108383,181.67
2864,0x749348cc3fc56d44a81aa1f6204e2cbdef932c1bcc87...,8514664,1568018288,9/9/2019 8:38:08 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,19.999461,0.000534,0.116125,180.84
2865,0xd302fc298f365deb10ec56816d98a851ec6ca7f9df53...,8515134,1568024689,9/9/2019 10:24:49 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.756728,0.000713,0.154833,180.84

### Pre-Processing

In [52]:
dfs=dfs.drop(['Txhash','Blockno','UnixTimestamp','DateTime','From','To'],axis=1)
dfs=dfs.dropna()
display(dfs)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
0           4.370434     0.000164     0.035679                 670.04
1           4.994791     0.000204     0.044242                 670.04
2           4.159414     0.000204     0.044242                 670.04
3           4.100858     0.000328     0.071358                 670.04
4           4.586255     0.000230     0.049950                 670.04
...              ...          ...          ...                    ...
2861       17.585908     0.000713     0.154833                 169.47
2862       14.273986     0.000784     0.170316                 169.47
2863       17.999538     0.000499     0.108383                 181.67
2864       19.999461     0.000534     0.116125                 180.84
2865        3.756728     0.000713     0.154833                 180.84

[2866 rows x 4 columns]

## Splitting the data

In [53]:
train, test = model_selection.train_test_split(dfs,test_size=0.25, random_state=101)
display(train)
display(test)

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
369         3.094432     0.000053     0.011417                 408.81
776         8.441675     0.000356     0.077418                 225.26
969         4.101445     0.000285     0.061933                 211.29
168         3.277096     0.000099     0.021479                 453.42
452         3.907891     0.000249     0.054191                 288.02
...              ...          ...          ...                    ...
599         4.663649     0.000214     0.046450                 220.12
1599       10.333396     0.000356     0.077416                 134.28
1361        7.831752     0.000321     0.069675                 139.73
1547        8.508002     0.000285     0.061936                 119.49
863        10.563648     0.000356     0.077416                 201.23

[2149 rows x 4 columns]

      Value_OUT(ETH)  TxnFee(ETH)  TxnFee(USD)  Historical $Price/Eth
2837       23.999004     0.000470     0.102190                 175.01
958         6.664611     0.000392     0.085158                 217.99
2629       14.440078     0.000285     0.061933                 217.22
59          4.013837     0.000263     0.057086                 668.38
459         3.844328     0.000178     0.038708                 295.55
...              ...          ...          ...                    ...
1473        8.077219     0.000274     0.059611                 116.33
44          4.210105     0.000263     0.057086                 727.41
2636       20.216069     0.000178     0.038708                 212.21
368         3.907328     0.000053     0.011417                 406.91
19          3.238351     0.000197     0.042815                 747.79

[717 rows x 4 columns]

### Training and testing the model

In [54]:
model = IsolationForest(contamination=0.01,random_state=101)
train['anamoly']=model.fit_predict(train)
a=train.loc[train['anamoly']==-1]
test['anamoly']=model.predict(test)
y_pred=test['anamoly']
acc=(y_pred==-1).sum()/test.shape[0]
print("The Accuracy of the following anamoly detection unit is ", (1-acc)*100,"%")
avg+=acc

<ipython-input-54-bf5b250f45fd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['anamoly']=model.fit_predict(train)
<ipython-input-54-bf5b250f45fd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['anamoly']=model.predict(test)

The Accuracy of the following anamoly detection unit is  98.88423988842399 %

### Transactions which has been marked as anamoly

In [55]:
(y_pred==-1).sum()
b=test.loc[test['anamoly']==-1]

c=pd.concat([a,b])
merged_left = pd.merge(left=dfs1, right=c, how='right',sort=True)
display(merged_left)

,Txhash,Blockno,UnixTimestamp,DateTime,From,To,Value_OUT(ETH),TxnFee(ETH),TxnFee(USD),Historical $Price/Eth,anamoly
0,0xceeb8110b9352de10443b09a4533b7600b4504a9fead...,6162811,1534495991,8/17/2018 8:53:11 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.116637,0.002003,0.435282,317.57,-1
1,0xb22738ce170b6234ebb94c736120f473b50626a7bcee...,5880869,1530364496,6/30/2018 1:14:56 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.225723,0.002496,0.542319,453.42,-1
2,0xf2e455c4d108fe21ad55c2ee243ce7cd43a9c5096701...,5890908,1530512115,7/2/2018 6:15:15 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.270322,0.002397,0.520911,476.58,-1
3,0xde7aff23bcdcccd8875d8706c3a344abf828de8c72a5...,6108640,1533705213,8/8/2018 5:13:33 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.285262,0.001970,0.428146,355.57,-1
4,0x71f4dba9938281563f7586fdceaa4f60c9628866d1e6...,6112139,1533755727,8/8/2018 7:15:27 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.297090,0.001970,0.428146,355.57,-1
5,0xb7952f3daedb63326dea16642836dc4a441240d3fdae...,6108196,1533698558,8/8/2018 3:22:38 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.351379,0.001970,0.428146,355.57,-1
6,0x9e5afaa2a6303b164ea05e811019704d0a541cc01d87...,6111096,1533740688,8/8/2018 3:04:48 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.395914,0.002003,0.435282,355.57,-1
7,0xc776cd98444ccb797c2d3ebd5c3440ddbde00b140e3c...,5898692,1530627013,7/3/2018 2:10:13 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.417805,0.003718,0.807823,461.95,-1
8,0x5a256711f1321ee85fe023a90a83c1e59f0e7f77d720...,5895985,1530586908,7/3/2018 3:01:48 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.434114,0.003054,0.663627,461.95,-1
9,0x4cf9edf82821f9737090b5b245318c627201d91284c4...,5897866,1530614869,7/3/2018 10:47:49 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.455681,0.003718,0.807823,461.95,-1
10,0xf186898bb8d5f03271277e7482b5890163bd0685f433...,5896155,1530589355,7/3/2018 3:42:35 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.506955,0.003087,0.670763,461.95,-1
11,0xca54c3a42bd2a99fbc23a45a208dbf4f4cdc031e604d...,5896888,1530600136,7/3/2018 6:42:16 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.513957,0.002857,0.620812,461.95,-1
12,0xc87b871f1f9bca36c2b69d68efef8de873eee64fd81d...,5895600,1530580872,7/3/2018 1:21:12 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.525235,0.002036,0.442418,461.95,-1
13,0x083a3b5451c1ab03bad69e2155f2d956596f6e0f98d8...,5885542,1530433711,7/1/2018 8:28:31 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.536281,0.002089,0.453835,451.95,-1
14,0x60c9b5474b84b87cda0ee4bb04dddb37314b240f7025...,5898228,1530620273,7/3/2018 12:17:53 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.562927,0.002791,0.606541,461.95,-1
15,0x8e2820fee4bf419d117e35da334cd15345878379c0b8...,5892879,1530541503,7/2/2018 2:25:03 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.804855,0.003718,0.807823,476.58,-1
16,0xd6766daffacc7851bd04900b775f630fa2b7ba1eb35a...,5922549,1530980804,7/7/2018 4:26:44 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.895239,0.002463,0.535183,485.81,-1
17,0x1958e77704398be208bb450b691b1fc314f9ff80a1f3...,5920636,1530952783,7/7/2018 8:39:43 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.927836,0.002283,0.496139,485.81,-1
18,0x0aa3073c47bb540299aa7c334a2e16d1276055725c36...,5969565,1531669149,7/15/2018 3:39:09 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,3.983974,0.003718,0.807823,449.62,-1
19,0x3da8526fe0fd9bd94a36770def9279c0553e270b4c89...,5904530,1530713891,7/4/2018 2:18:11 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.159709,0.002332,0.506640,467.19,-1
20,0x8827f5051d543b4b39b0651071513468df6dabcb45a0...,5903735,1530701718,7/4/2018 10:55:18 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.186490,0.002332,0.506640,467.19,-1
21,0xa506e29a9827809f05fd3d6d77da227b53a09cee2d4c...,5963155,1531577028,7/14/2018 2:03:48 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.296498,0.003612,0.784935,433.74,-1
22,0xedf64bf069737a232200539793ff4a238f5fbb5eacea...,6111507,1533746699,8/8/2018 4:44:59 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.335341,0.002003,0.435282,355.57,-1
23,0x5ed7061bc446f9fcefaf461df49ea231b89343de9f83...,6114837,1533795230,8/9/2018 6:13:50 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.402565,0.001970,0.428146,363.51,-1
24,0x2ab9d48a6bbb19455e836fa91e6803262887fc46c2ba...,5897406,1530608038,7/3/2018 8:53:58 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.460728,0.002890,0.627948,461.95,-1
25,0xaa8abbf1fe1035ad799e0d5b72a28b2e97d3341708ae...,5895825,1530584440,7/3/2018 2:20:40 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.579561,0.002956,0.642220,461.95,-1
26,0x51321f07a539f3491ce7361f0c9664427ff48428d58a...,5919889,1530941386,7/7/2018 5:29:46 AM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,4.922424,0.002299,0.499504,485.81,-1
27,0x731eea721ba3d0f57d9560448a299b398730e05a6625...,5915981,1530883441,7/6/2018 1:24:01 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,5.003874,0.003284,0.713577,469.93,-1
28,0xc2bd4f2d17de8856ae74c3a86e5c6babdbd6708a8472...,6105078,1533653049,8/7/2018 2:44:09 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,5.406992,0.001970,0.428146,377.94,-1
29,0x3ace85a0d77b8ba0564774fa0d63931ef7d544928d20...,5899387,1530637537,7/3/2018 5:05:37 PM,0xfc04f920c7195b75fbb3b387c9a3dbfa8d10f651,0xfa52274dd61e1643d2205169732f29114bc240b3,5.451795,0.002627,0.570862,461.95,-1

In [56]:
print("The average accuracies of all the transaction is",100-avg*10)

The average accuracies of all the transaction is 99.21085672087055